table EmployeeBasicInfo
	lineageTag: b7fd8bfc-d16e-4092-965a-0605a861dac3

	column EmployeeNo
		dataType: string
		lineageTag: daef7094-0ddb-4e8b-9af4-474f316478a0
		summarizeBy: none
		sourceColumn: EmployeeNo

		annotation SummarizationSetBy = Automatic

	column Person_ID
		dataType: int64
		formatString: 0
		lineageTag: 5cf38f65-4f0a-453b-91d2-a1579b1a669f
		summarizeBy: none
		sourceColumn: Person_ID

		annotation SummarizationSetBy = Automatic

	column 'Therapist Name'
		dataType: string
		lineageTag: 43f58bc9-c689-4401-9fcc-ea0b8fc12733
		summarizeBy: none
		sourceColumn: Therapist Name

		annotation SummarizationSetBy = Automatic

	column JobTitle
		dataType: string
		lineageTag: bc432d8f-a035-4ad4-8b27-eae5bb90f6c1
		summarizeBy: none
		sourceColumn: JobTitle

		annotation SummarizationSetBy = Automatic

	column Credentials
		dataType: string
		lineageTag: 64b9b580-0aaf-4d1c-b027-71fcfa0f429a
		summarizeBy: none
		sourceColumn: Credentials

		annotation SummarizationSetBy = Automatic

	column 'Therapist Label' = EmployeeBasicInfo[Therapist Name]&" ("&EmployeeBasicInfo[JobTitle]&")"
		lineageTag: c35bfe96-babf-4431-968d-6408045e260e
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition EmployeeBasicInfo = m
		mode: import
		queryGroup: People
		source =
				let
				    Source = PowerPlatform.Dataflows(null),
				    Workspaces = Source{[Id="Workspaces"]}[Data],
				    #"538303cf-865c-4aae-b405-89ef5e1991aa" = Workspaces{[workspaceId="538303cf-865c-4aae-b405-89ef5e1991aa"]}[Data],
				    #"5850e03f-8c48-4d08-8182-7cf99d360333" = #"538303cf-865c-4aae-b405-89ef5e1991aa"{[dataflowId="5850e03f-8c48-4d08-8182-7cf99d360333"]}[Data],
				    EmployeeBasicInfo_ = #"5850e03f-8c48-4d08-8182-7cf99d360333"{[entity="EmployeeBasicInfo",version=""]}[Data],
				    #"Removed Other Columns" = Table.SelectColumns(EmployeeBasicInfo_,{"LastName", "FirstName", "JobTitle", "EmployeeNo", "Person_ID", "Credentials"}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Removed Other Columns",{{"EmployeeNo", type text}}),
				    #"Filtered Rows" = Table.SelectRows(#"Changed Type", each ([EmployeeNo] <> "99999")),
				    #"Filtered Rows1" = Table.SelectRows(#"Filtered Rows", each [Person_ID] <> null and [Person_ID] <> ""),
				    #"Merged Columns" = Table.CombineColumns(#"Filtered Rows1",{"FirstName", "LastName"},Combiner.CombineTextByDelimiter(" ", QuoteStyle.None),"Therapist Name")
				in
				    #"Merged Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

