table Perspectives
	lineageTag: db30dcdf-20f0-4259-a2e7-656c3dbd9ad7

	column FacilityId
		dataType: string
		lineageTag: da3429fb-a527-4c10-b93b-657472f1a1cb
		summarizeBy: none
		sourceColumn: FacilityId

		annotation SummarizationSetBy = Automatic

	column UPN
		dataType: string
		lineageTag: 91a9d736-e6e2-4420-a902-22ca93e89bd0
		summarizeBy: none
		sourceColumn: UPN

		annotation SummarizationSetBy = Automatic

	partition Perspectives = m
		mode: import
		queryGroup: People
		source =
				let
				    //UPN table
				    UPN_Source = dbo_vw_UpnFacilityAccess,
				    Contracts_Table = Salesforce_Aegis_Contract,
				    Contracts_RemovedOtherColumns = Table.SelectColumns(Contracts_Table,{"Contract_Number__c"}),
				    Contracts_RenamedColumns = Table.RenameColumns(Contracts_RemovedOtherColumns,{{"Contract_Number__c", "FacilityId"}}),
				    Contracts_AddedCustom = Table.AddColumn(Contracts_RenamedColumns, "UPN", each "kolby.mangino@healthcraftcreative.com;sara.mcolvin@healthcraftcreative.com;mark.besch@aegistherapies.com;brad.miller@aegistherapies.com;dawn.greaves@aegistherapies.com;jaclyn.warshauer@aegistherapies.com;jason.buss@aegistherapies.com"),
				    Contracts_SplitColumnbyDelimiter = Table.SplitColumn(Contracts_AddedCustom, "UPN", Splitter.SplitTextByDelimiter(";", QuoteStyle.Csv), {"UPN.1", "UPN.2", "UPN.3", "UPN.4", "UPN.5", "UPN.6", "UPN.7"}),
				    Contracts_UnpivotedOtherColumns = Table.UnpivotOtherColumns(Contracts_SplitColumnbyDelimiter, {"FacilityId"}, "Attribute", "Value"),
				    Contracts_RemovedColumns = Table.RemoveColumns(Contracts_UnpivotedOtherColumns,{"Attribute"}),
				    Contracts_RenamedColumns2 = Table.RenameColumns(Contracts_RemovedColumns,{{"Value", "UPN"}}),
				
				    //Combine
				    Combine_Append = Table.Combine({UPN_Source, Contracts_RenamedColumns2}),
				    Combine_TrimmedText = Table.TransformColumns(Combine_Append,{{"FacilityId", Text.Trim, type text}}),
				    Combine_AddedPrefix = Table.TransformColumns(Combine_TrimmedText, {{"FacilityId", each "000" & _, type text}}),
				    Combine_ExtractedLastCharacters = Table.TransformColumns(Combine_AddedPrefix, {{"FacilityId", each Text.End(_, 5), type text}}),
				    Combine_LowercasedText = Table.TransformColumns(Combine_ExtractedLastCharacters,{{"UPN", Text.Lower, type text}}),
				    Combine_RemovedDuplicates = Table.Distinct(Combine_LowercasedText)
				in
				    Combine_RemovedDuplicates

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

