/// vw_AllEvalsAndDischargesLight_Items
table Assessments
	lineageTag: 8a1a4fb5-071b-4eb4-8fb0-4ca6b515119d

	measure 'Avg Score' =
			
			AVERAGEX(
			    Assessments,
			    RELATED('Outcomes Custom Scales'[Points])
			)
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: 1901dc20-70b9-4c5b-92e5-1e3ef9f09bf7

	measure 'Total Assessments' = COUNTROWS(Assessments)
		formatString: #,0
		lineageTag: 34bf68e3-4b5b-4e75-928b-12e4b5ea0c71

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Total Questions' = DISTINCTCOUNT(Assessments[LibraryItem_ID])
		lineageTag: a2332deb-73de-451a-a236-042f8478b5a6

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Raw Admit' =
			
			CALCULATE(
			    [Avg Score],
			    Documents[DocumentType]="ADMIT"
			)
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: 46c252cf-cde5-47a3-ab97-c769b5df23e5

	measure 'Raw Discharge' =
			
			CALCULATE(
			    [Avg Score],
			    Documents[DocumentType]="DISCH"
			)
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: d6e318dd-830b-4f54-998d-e2adacc8a4b8

	measure 'Raw Admit Pain' =
			
			CALCULATE(
			    [Avg Score],
			    Documents[DocumentType]="ADMIT",
			    'Outcomes Crosswalk'[Name]="Pain at rest or w/ activity",
			    'Outcomes Custom Scales'[Points]<1
			)
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: b43a1c97-eee3-41a3-a5fe-868911f97563

	measure '% ANA Responses' = ```
			
			var num = 
			CALCULATE(
			    [Total Assessments],
			    'Outcomes Custom Scales'[Response Type]="N/A",
			    'Outcomes Crosswalk'[Family] IN {"(a) Section GG Mobility", "(b) Section GG Self Care"}
			)
			
			var den = 
			CALCULATE(
			    [Total Assessments],
			    'Outcomes Crosswalk'[Family] IN {"(a) Section GG Mobility", "(b) Section GG Self Care"}
			)
			
			return DIVIDE(num,den)
			```
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: 2829227c-0e39-41cc-8fdb-a87523d20d5c

	measure 'Total GG ANA Responses' =
			
			CALCULATE(
			    [Total Assessments],
			    'Outcomes Custom Scales'[Response Type]="N/A",
			    'Outcomes Crosswalk'[Family] IN {"(a) Section GG Mobility", "(b) Section GG Self Care"}
			)
		formatString: #,0
		lineageTag: 316765ec-5be6-42c6-ad9f-75bc574b2bc2

	measure 'Total GG Assessments' =
			
			CALCULATE(
			    [Total Assessments],
			    'Outcomes Crosswalk'[Family] IN {"(a) Section GG Mobility", "(b) Section GG Self Care"}
			)
		formatString: #,0
		lineageTag: cc525a31-5cf4-4f73-bd50-9ee95476d4f2

	column TxDocument_ID
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 329c6824-9024-4b00-9712-e1a09b5c6289
		summarizeBy: none
		sourceColumn: TxDocument_ID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column LibraryItem_ID
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 3746f799-9b14-4220-8e70-da6f45ba1c47
		summarizeBy: none
		sourceColumn: LibraryItem_ID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column LibraryScaleValue_ID
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 860b33f1-d61f-42c8-a2d1-49204e60f1f9
		summarizeBy: none
		sourceColumn: LibraryScaleValue_ID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition Assessments = m
		mode: import
		queryGroup: Outcomes
		source =
				let
				    Source = #"dbo vw_AllEvalsAndDischargesLight_Items",
				    #"Filtered Rows" = Table.SelectRows(Source, each [LibraryScaleValue_ID] <> null and [LibraryScaleValue_ID] <> ""),
				    #"Merged Queries" = Table.NestedJoin(#"Filtered Rows", {"LibraryItem_ID"}, #"Outcomes Crosswalk", {"LibraryItem_ID"}, "Outcomes Crosswalk", JoinKind.Inner)
				in
				    #"Merged Queries"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

