table Facility
	lineageTag: de02e475-22e0-4ffd-9682-602f87e12fca

	measure 'Total Facilities' = COUNTROWS(Facility)
		formatString: #,0
		lineageTag: 0542289a-e6a2-49ef-956b-0c976e63675d

	measure 'Total Facilities by Division' =
			
			CONCATENATEX(
			    SUMMARIZE(Facility, Facility[DivisionName]),
			    Facility[DivisionName] & ": " & FORMAT(CALCULATE(COUNTROWS(Facility)), "#,0"),
			    ", ",
			    Facility[DivisionName], ASC
			)
		lineageTag: 68bf6dbc-c129-4754-b605-5a1017fffeec

	measure 'Live Edit Test' = "If you can see this, live reload really works!"
		lineageTag: 025a11a9-d4af-423e-81a4-cdda42117562

	column Facility_ID
		dataType: int64
		isHidden
		isKey
		lineageTag: fe518494-d5fa-4129-8c80-2a0d909381c7
		summarizeBy: none
		sourceColumn: Facility_ID

	column FacilityName
		dataType: string
		lineageTag: e45542c9-5053-43f0-98a8-a8069b1f3c5e
		summarizeBy: none
		sourceColumn: FacilityName

	column FacilityCode
		dataType: string
		lineageTag: c149e34a-713a-438c-a561-851fa5c7bbd7
		summarizeBy: none
		sourceColumn: FacilityCode

	column SiteType
		dataType: string
		lineageTag: 328a2b85-8fbc-42b6-b519-858bec01bc6f
		summarizeBy: none
		sourceColumn: SiteType

	column DivisionName
		dataType: string
		lineageTag: 2af1145a-dfd7-465c-a7eb-1943e03e4970
		summarizeBy: none
		sourceColumn: DivisionName

	column RegionName
		dataType: string
		lineageTag: 9c3b0de3-6589-4f1c-b409-92402313fbcd
		summarizeBy: none
		sourceColumn: RegionName

	column AreaName
		dataType: string
		lineageTag: 6c57a978-5aa6-438a-876d-7b8dc2673ecb
		summarizeBy: none
		sourceColumn: AreaName

	partition Facility = m
		mode: import
		source =
				let
					Source = Sql.Database("asot7hu5ofuezkzklqea75om6i-vox2z5x5nsnuri4qviabf7xo3i.datawarehouse.fabric.microsoft.com", "Aegis_Core_Silver_Lakehouse"),
					Data = Value.NativeQuery(Source, "SELECT f.NetHealthId AS Facility_ID, f.Name AS FacilityName, f.FacilityNumber AS FacilityCode, f.SiteType, fh.RegionName AS DivisionName, fh.AreaName AS RegionName, fh.DistrictName AS AreaName FROM dbo.facility f LEFT JOIN dbo.facilityhierarchy fh ON f.FacilityNumber = fh.FacilityNumber WHERE fh.RegionNumber IN ('08450', '05500', '06500')", null, [EnableFolding=true])
				in
					Data

