// =============================================================================
// Therapist Total Weighted Tracks - Simplified attribution-only query
// =============================================================================
// Validates attribution logic: Contribution_Pct = avg(Visit_Pct, Minute_Pct) per track
// Total_Weighted_Tracks = sum of Contribution_Pct per therapist
// =============================================================================

EVALUATE
VAR ValidTrackIDs =
    SELECTCOLUMNS (
        FILTER (
            ADDCOLUMNS (
                VALUES ( CaseTracks[TxTrack_ID] ),
                "@Duration", CALCULATE ( [Track Duration] ),
                "@Admit", CALCULATE ( [Admit Level] ),
                "@Discharge", CALCULATE ( [Discharge Level] )
            ),
            [@Duration] > 5
                && NOT ( ISBLANK ( [@Admit] ) )
                && NOT ( ISBLANK ( [@Discharge] ) )
        ),
        "TxTrack_ID", CaseTracks[TxTrack_ID]
    )
VAR __DateRange =
    FILTER ( VALUES ( 'Calendar'[Date] ), 'Calendar'[Date] >= TODAY () - 365 )
VAR AttributionBase =
    CALCULATETABLE (
        SUMMARIZECOLUMNS (
            Employees[Person_ID],
            Employees[Name],
            Employees[StaffTitle],
            CaseTracks[TxTrack_ID],
            CaseTracks[Discipline],
            TREATAS ( ValidTrackIDs, CaseTracks[TxTrack_ID] ),
            "Total_Visits", [Total Visits],
            "Total_Minutes", [Total Minutes],
            "Track_Visits", CALCULATE ( [Total Visits], REMOVEFILTERS ( Employees ) ),
            "Track_Minutes", CALCULATE ( [Total Minutes], REMOVEFILTERS ( Employees ) ),
            "@One", 1
        ),
        KEEPFILTERS ( __DateRange ),
        KEEPFILTERS ( NOT ( ISBLANK ( 'DischargeDestination'[Lookup_ID] ) ) ),
        KEEPFILTERS ( NOT ( ISBLANK ( 'Aegis Contract'[Contract_Number__c] ) ) ),
        KEEPFILTERS ( 'Calendar'[ReliableScope] = TRUE () )
    )
VAR AttributionWithPct =
    ADDCOLUMNS (
        AttributionBase,
        "Contribution_Pct", DIVIDE (
            DIVIDE ( [Total_Visits], [Track_Visits], 0 ) + DIVIDE ( [Total_Minutes], [Track_Minutes], 0 ),
            2,
            0
        )
    )
VAR ByTherapist =
    GROUPBY (
        AttributionWithPct,
        [Person_ID],
        [Name],
        [StaffTitle],
        "Total_Tracks", SUMX ( CURRENTGROUP (), [@One] ),
        "Total_Weighted_Tracks", SUMX ( CURRENTGROUP (), [Contribution_Pct] )
    )
VAR FilteredTherapists = FILTER ( ByTherapist, [Total_Tracks] >= 25 )
RETURN
    FilteredTherapists
