/// One row per facility (>= 50 episodes in the window). OverallResidual = mean observed-minus-
/// expected across the facility's case-items; the single-number summary the per-item view unpacks.
/// DivisionName is the NetHealth Region (Division 8450/5500/6500). Facility RLS is a future step
/// (needs the UPN -> facility security mapping used by the ClinicalOutcomes model).
table DimFacility
	lineageTag: 22b30002-0002-4b02-8c02-200000000001

	column Facility_ID
		dataType: int64
		isKey
		formatString: 0
		lineageTag: 22b30002-0002-4b02-8c02-200000000002
		summarizeBy: none
		sourceColumn: Facility_ID

		annotation SummarizationSetBy = Automatic

	column FacilityName
		dataType: string
		lineageTag: 22b30002-0002-4b02-8c02-200000000003
		summarizeBy: none
		sourceColumn: FacilityName

		annotation SummarizationSetBy = Automatic

	column DivisionName
		dataType: string
		lineageTag: 22b30002-0002-4b02-8c02-200000000004
		summarizeBy: none
		sourceColumn: DivisionName

		annotation SummarizationSetBy = Automatic

	column TotalCases
		dataType: int64
		formatString: #,0
		lineageTag: 22b30002-0002-4b02-8c02-200000000005
		summarizeBy: sum
		sourceColumn: TotalCases

		annotation SummarizationSetBy = Automatic

	column OverallResidual
		dataType: double
		formatString: +0.00;-0.00;0.00
		lineageTag: 22b30002-0002-4b02-8c02-200000000006
		summarizeBy: none
		sourceColumn: OverallResidual

		annotation SummarizationSetBy = Automatic

	partition DimFacility = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\KLM0001\Documents\Dev\Work\fabric-data\data\item-facility-feed.csv"), [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
				    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				    Kept = Table.SelectColumns(Promoted, {"Facility_ID", "FacilityName", "DivisionName", "TotalCases", "OverallResidual"}),
				    Typed = Table.TransformColumnTypes(Kept, {{"Facility_ID", Int64.Type}, {"FacilityName", type text}, {"DivisionName", type text}, {"TotalCases", Int64.Type}, {"OverallResidual", type number}})
				in
				    Typed

	annotation PBI_ResultType = Table
