/// One row per (Facility x Section GG item) from the per-item risk-adjusted analysis
/// (analysis/item_scorecard.py -> build_item_feed.py). Residual = observed - expected
/// discharge score, native 6-point GG scale, where Expected comes from a givens-only,
/// out-of-fold model. Cells with < 15 episodes are dropped upstream. Dev source = local
/// committed CSV; production = IT-ingested medallion table (same trailing-12-mo window).
table FactItemResidual
	lineageTag: 11a20001-0001-4a01-8b01-100000000001

	measure 'Obs - Exp' = AVERAGE(FactItemResidual[Residual])
		formatString: +0.00;-0.00;0.00
		lineageTag: 11a20001-0001-4a01-8b01-100000000002

	measure 'Avg Observed' = AVERAGE(FactItemResidual[Observed])
		formatString: 0.00
		lineageTag: 11a20001-0001-4a01-8b01-100000000003

	measure 'Avg Expected' = AVERAGE(FactItemResidual[Expected])
		formatString: 0.00
		lineageTag: 11a20001-0001-4a01-8b01-100000000004

	measure 'Avg Gain' = AVERAGE(FactItemResidual[Gain])
		formatString: +0.00;-0.00;0.00
		lineageTag: 11a20001-0001-4a01-8b01-100000000005

	measure '% >= Expected' = AVERAGE(FactItemResidual[PctGeExp]) / 100
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: 11a20001-0001-4a01-8b01-100000000006

	measure 'Total Episodes' = SUM(FactItemResidual[Episodes])
		formatString: #,0
		lineageTag: 11a20001-0001-4a01-8b01-100000000007

	column Facility_ID
		dataType: int64
		formatString: 0
		lineageTag: 11a20001-0001-4a01-8b01-100000000010
		summarizeBy: none
		sourceColumn: Facility_ID

		annotation SummarizationSetBy = Automatic

	column ItemCode
		dataType: int64
		formatString: 0
		lineageTag: 11a20001-0001-4a01-8b01-100000000011
		summarizeBy: none
		sourceColumn: ItemCode

		annotation SummarizationSetBy = Automatic

	column Episodes
		dataType: int64
		formatString: 0
		lineageTag: 11a20001-0001-4a01-8b01-100000000012
		summarizeBy: none
		sourceColumn: Episodes

		annotation SummarizationSetBy = Automatic

	column Admission
		dataType: double
		isHidden
		lineageTag: 11a20001-0001-4a01-8b01-100000000013
		summarizeBy: none
		sourceColumn: Admission

		annotation SummarizationSetBy = Automatic

	column Observed
		dataType: double
		isHidden
		lineageTag: 11a20001-0001-4a01-8b01-100000000014
		summarizeBy: none
		sourceColumn: Observed

		annotation SummarizationSetBy = Automatic

	column Expected
		dataType: double
		isHidden
		lineageTag: 11a20001-0001-4a01-8b01-100000000015
		summarizeBy: none
		sourceColumn: Expected

		annotation SummarizationSetBy = Automatic

	column Gain
		dataType: double
		isHidden
		lineageTag: 11a20001-0001-4a01-8b01-100000000016
		summarizeBy: none
		sourceColumn: Gain

		annotation SummarizationSetBy = Automatic

	column Residual
		dataType: double
		isHidden
		lineageTag: 11a20001-0001-4a01-8b01-100000000017
		summarizeBy: none
		sourceColumn: Residual

		annotation SummarizationSetBy = Automatic

	column PctGeExp
		dataType: double
		isHidden
		lineageTag: 11a20001-0001-4a01-8b01-100000000018
		summarizeBy: none
		sourceColumn: PctGeExp

		annotation SummarizationSetBy = Automatic

	partition FactItemResidual = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\KLM0001\Documents\Dev\Work\fabric-data\data\item-fact-feed.csv"), [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
				    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				    Kept = Table.SelectColumns(Promoted, {"Facility_ID", "ItemCode", "Episodes", "Admission", "Observed", "Expected", "Gain", "Residual", "PctGeExp"}),
				    Typed = Table.TransformColumnTypes(Kept, {{"Facility_ID", Int64.Type}, {"ItemCode", Int64.Type}, {"Episodes", Int64.Type}, {"Admission", type number}, {"Observed", type number}, {"Expected", type number}, {"Gain", type number}, {"Residual", type number}, {"PctGeExp", type number}})
				in
				    Typed

	annotation PBI_ResultType = Table
