/// Admit and discharge dates for each patient's episode
table PatientStays
	lineageTag: 40351199-8ac4-4405-95a4-c849ef65ff3a

	measure 'Total Stays' = COUNTROWS(PatientStays)
		formatString: #,0
		lineageTag: 3f201725-2e9f-48fe-a992-35e66767c77b

	column PatientID
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 175e276d-2e6f-4ed5-b6f7-c7d80d3f6885
		summarizeBy: none
		sourceColumn: PatientID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Stay_ID
		dataType: int64
		isHidden
		isKey
		formatString: 0
		lineageTag: 9416b9cf-f885-4a0f-9b7e-c22dccce5c2e
		summarizeBy: none
		sourceColumn: Stay_ID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column AdmitDate
		dataType: dateTime
		formatString: Short Date
		lineageTag: 6450bd16-900b-4dda-8a2f-804f3a70e5f5
		summarizeBy: none
		sourceColumn: AdmitDate

		variation Variation
			isDefault
			relationship: 2df048c0-06d5-4e15-a646-80700923a8ba
			defaultHierarchy: LocalDateTable_9c24de53-d4f5-49d1-8e5b-244c6b3313c7.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column DischargeDate
		dataType: dateTime
		formatString: Short Date
		lineageTag: cf7f7ad8-5877-464e-9724-35fc2387c2fd
		summarizeBy: none
		sourceColumn: DischargeDate

		variation Variation
			isDefault
			relationship: b1e45dbd-421e-446d-8563-08169ffe9d19
			defaultHierarchy: LocalDateTable_d3bfd21e-b0d5-4dc1-97fb-5b07e40b03f7.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column IntakeSource_ID
		dataType: int64
		formatString: 0
		lineageTag: f1226adc-37ff-460a-b0c7-b1394e758d23
		summarizeBy: none
		sourceColumn: IntakeSource_ID

		annotation SummarizationSetBy = Automatic

	partition PatientStays = m
		mode: import
		queryGroup: Patient
		source =
				let
				    Source = dbo_vw_PatientStays,
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"AdmitDate", type date}, {"DischargeDate", type date}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

