table Physician
	lineageTag: 0c225407-294b-4b55-9da5-8d958606d30c

	measure 'Total Physicians' = COUNTROWS(Physician)
		formatString: #,0
		lineageTag: 82353ea2-abcb-494d-a79b-5c7dcc64792e

	column Physician_ID
		dataType: int64
		isKey
		formatString: 0
		lineageTag: 9b2847c0-2b8d-44e8-9876-f15064df06ec
		summarizeBy: none
		sourceColumn: Physician_ID

		annotation SummarizationSetBy = Automatic

	column Name
		dataType: string
		lineageTag: 9c0f4a34-643d-4a14-91ca-4492b6a09baa
		summarizeBy: none
		sourceColumn: Name

		annotation SummarizationSetBy = Automatic

	column NPI
		dataType: string
		lineageTag: d36c6128-b903-433c-ad21-12f8fb745f83
		summarizeBy: none
		sourceColumn: NPI

		annotation SummarizationSetBy = Automatic

	partition Physician = m
		mode: import
		queryGroup: Provider
		source =
				let
				    Source = PowerPlatform.Dataflows(null),
				    Workspaces = Source{[Id="Workspaces"]}[Data],
				    #"58ac0bf7-44e5-4241-a12e-4c6f42ba8a78" = Workspaces{[workspaceId="58ac0bf7-44e5-4241-a12e-4c6f42ba8a78"]}[Data],
				    #"1f384293-8e92-485c-bde7-4681f9cb36ca" = #"58ac0bf7-44e5-4241-a12e-4c6f42ba8a78"{[dataflowId="1f384293-8e92-485c-bde7-4681f9cb36ca"]}[Data],
				    Physician_ = #"1f384293-8e92-485c-bde7-4681f9cb36ca"{[entity="Physician",version=""]}[Data],
				    #"Removed Other Columns" = Table.SelectColumns(Physician_,{"Physician_ID", "FirstName", "LastName", "NPI"}),
				    #"Merged Columns" = Table.CombineColumns(#"Removed Other Columns",{"FirstName", "LastName"},Combiner.CombineTextByDelimiter(" ", QuoteStyle.None),"Name")
				in
				    #"Merged Columns"

	annotation PBI_ResultType = Table

