table PatientLevelOptionalServices_Instance
	lineageTag: e573f993-d4f5-4614-ab71-a1d1fc0aefa1

	column Resident_ID
		dataType: int64
		formatString: 0
		lineageTag: 07da1270-ca17-4862-bbca-6fef9f6dd46c
		summarizeBy: none
		sourceColumn: Resident_ID

		annotation SummarizationSetBy = Automatic

	column Service_ID
		dataType: string
		lineageTag: 788d916a-1597-4717-b7d2-87838bac6ac1
		summarizeBy: none
		sourceColumn: Service_ID

		annotation SummarizationSetBy = Automatic

	column CreatedDate
		dataType: dateTime
		formatString: General Date
		lineageTag: e7c0caba-64b2-4e47-b906-97ddeb674c7a
		summarizeBy: none
		sourceColumn: CreatedDate

		variation Variation
			isDefault
			relationship: 39a24c88-290c-40a0-875b-e1a0ed2e06d7
			defaultHierarchy: LocalDateTable_e9e917f2-5178-4525-99ea-dc96c0ad92c2.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	partition PatientLevelOptionalServices_Instance = m
		mode: import
		queryGroup: Patient
		source =
				let
				    Source = PowerPlatform.Dataflows(null),
				    Workspaces = Source{[Id="Workspaces"]}[Data],
				    #"85b4966e-36ff-4433-990a-06a46dbbba67" = Workspaces{[workspaceId="85b4966e-36ff-4433-990a-06a46dbbba67"]}[Data],
				    #"0ad806a7-7698-4083-ba4f-c42c5aa91ecc" = #"85b4966e-36ff-4433-990a-06a46dbbba67"{[dataflowId="0ad806a7-7698-4083-ba4f-c42c5aa91ecc"]}[Data],
				    PatientLevelOptionalServices_Instance_ = #"0ad806a7-7698-4083-ba4f-c42c5aa91ecc"{[entity="PatientLevelOptionalServices_Instance",version=""]}[Data],
				    #"Removed Other Columns" = Table.SelectColumns(PatientLevelOptionalServices_Instance_,{"Resident_ID", "Service_ID", "CreatedDate"})
				in
				    #"Removed Other Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

