table TreatmentsDetails
	lineageTag: 99167761-ad1c-420f-b9d1-fba565467ac0

	column SessionId
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 62217618-fe96-463e-9932-f2aec527e587
		summarizeBy: none
		sourceColumn: SessionId

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Duration
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 95f30447-d201-4cbf-93f4-24d5b150e68e
		summarizeBy: sum
		sourceColumn: Duration

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Units
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: a9cfc8aa-c27e-433b-8966-d30c765cdd5f
		summarizeBy: sum
		sourceColumn: Units

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column ServiceCode
		dataType: string
		isHidden
		lineageTag: 38d1297c-ec8a-461e-b855-2ebe221b35f3
		summarizeBy: none
		sourceColumn: ServiceCode

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition TreatmentsDetails = m
		mode: import
		queryGroup: Visits
		source =
				let
				    Source = dbo_vw_Treatments,
				    #"Removed Other Columns" = Table.SelectColumns(Source,{"SessionId", "Duration", "Units", "ServiceCode"}),
				    #"Removed Duplicates" = Table.Distinct(#"Removed Other Columns", {"SessionId", "ServiceCode"})
				in
				    #"Removed Duplicates"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

