table CaseTracks
	lineageTag: 2f70d1c5-9fb4-4d9d-941b-5ce3ae7e833e

	measure 'Total Tracks' = COUNTROWS(CaseTracks)
		formatString: #,0
		lineageTag: 1ea16cd9-2277-418c-9247-407e5b7127e4

	measure 'Min Track Start' = MIN(CaseTracks[StartDate])
		formatString: Short Date
		lineageTag: 8c853bd8-baac-4971-9553-54f573b0b2f6

	measure 'Max Track End' = MAX(CaseTracks[EndDate])
		formatString: Short Date
		lineageTag: 0b208edd-95a4-4fde-aa15-820d858f21e4

	measure 'Track Duration' =
			
			DATEDIFF(
			    SELECTEDVALUE(CaseTracks[StartDate])-1,
			    SELECTEDVALUE(CaseTracks[EndDate]),
			    DAY
			)
		lineageTag: 10b54b7b-2897-4b99-95a2-f27fa591f12a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Track Start' = SELECTEDVALUE(CaseTracks[StartDate])
		lineageTag: 31431a88-e9e7-48c4-9a60-67cba3d2b128

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column TxTrack_ID
		dataType: int64
		isKey
		formatString: 0
		lineageTag: f709a6a9-1ecc-49d3-80f7-444932be70ec
		summarizeBy: none
		sourceColumn: TxTrack_ID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column PatientCase_ID
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 17432cc1-d58a-4ebf-9b8f-a2707eda26c1
		summarizeBy: none
		sourceColumn: PatientCase_ID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Discipline
		dataType: string
		isHidden
		lineageTag: 84244e05-f26e-48a8-82f3-6eae2f11ae37
		summarizeBy: none
		sourceColumn: Discipline

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column StartDate
		dataType: dateTime
		formatString: Short Date
		lineageTag: 8a906e0f-f580-4e1d-ad13-9f106f4d5587
		summarizeBy: none
		sourceColumn: StartDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column EndDate
		dataType: dateTime
		formatString: Short Date
		lineageTag: b1bfb695-b01d-4f69-9965-be761954bea4
		summarizeBy: none
		sourceColumn: EndDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	partition CaseTracks = m
		mode: import
		queryGroup: Patient
		source =
				let
				    Source = dbo_vw_CaseTracks,
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"StartDate", type date}, {"EndDate", type date}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation
