table DiagnosisCode
	lineageTag: 98fd4e14-52fd-41a5-adda-415c7e36b5e5

	column DiagnosisCode_ID
		dataType: int64
		isKey
		formatString: 0
		lineageTag: 00b2a219-e677-4dda-89a6-1062a9df3d7d
		summarizeBy: none
		sourceColumn: DiagnosisCode_ID

		annotation SummarizationSetBy = Automatic

	column L4
		dataType: string
		lineageTag: 836168e9-8713-4a0c-b00d-6ce1104b32a1
		summarizeBy: none
		sourceColumn: L4

		annotation SummarizationSetBy = Automatic

	column L3
		dataType: string
		lineageTag: ccf1dacc-2caf-4564-9238-8940bb9c302c
		summarizeBy: none
		sourceColumn: L3

		annotation SummarizationSetBy = Automatic

	column L2
		dataType: string
		lineageTag: 91a5c15a-3a66-446f-afac-03ab6d28a80e
		summarizeBy: none
		sourceColumn: L2

		annotation SummarizationSetBy = Automatic

	column L1
		dataType: string
		lineageTag: dc0c5302-d9fd-46c5-8f08-3fba858cb12f
		summarizeBy: none
		sourceColumn: L1

		annotation SummarizationSetBy = Automatic

	column ICD
		dataType: string
		lineageTag: 460b117b-b77a-4d45-ba61-26179e9420ef
		summarizeBy: none
		sourceColumn: ICD

		annotation SummarizationSetBy = Automatic

	partition DiagnosisCode = m
		mode: import
		queryGroup: Diagnoses
		source = ```
				let
				    //Sources: DiagnosisCode (L4/L3) from true Bronze; DiagnosisCategory (L2/L1) from aegisdataprod until it lands in Bronze
				
				    //Codes (L4 and L3)
				    Codes_GetName = Value.NativeQuery(_NetHealthBronze, "SELECT DiagnosisCode_ID, Code, Description, ParentDiagnosisCode_ID, DiagnosisCategory_ID FROM dbo.DiagnosisCode"),
				    Codes_RemovedOtherColumns = Table.SelectColumns(Codes_GetName,{"DiagnosisCode_ID", "Code", "Description", "ParentDiagnosisCode_ID", "DiagnosisCategory_ID"}),
				    Codes_DuplicatedColumn = Table.DuplicateColumn(Codes_RemovedOtherColumns, "Code", "ICD"),
				    Codes_MergeL4 = Table.CombineColumns(Codes_DuplicatedColumn,{"Code", "Description"},Combiner.CombineTextByDelimiter(": ", QuoteStyle.None),"L4"),
				    Codes_MergeForL3 = Table.NestedJoin(Codes_MergeL4, {"ParentDiagnosisCode_ID"}, Codes_MergeL4, {"DiagnosisCode_ID"}, "Codes_MergedColumns", JoinKind.LeftOuter),
				    Codes_ExpandL3 = Table.ExpandTableColumn(Codes_MergeForL3, "Codes_MergedColumns", {"L4"}, {"L3"}),
				    Codes_RemovedColumns = Table.RemoveColumns(Codes_ExpandL3,{"ParentDiagnosisCode_ID"}),
				
				    //Categories (L2 and L1)
				    Categories_GetName = Value.NativeQuery(_AegisPatient, "SELECT DiagnosisCategory_ID, Description, ParentDiagnosisCategory_ID FROM NetHealthDocumentation.DiagnosisCategory"),
				    Categories_RemovedOtherColumns = Table.SelectColumns(Categories_GetName,{"DiagnosisCategory_ID", "Description", "ParentDiagnosisCategory_ID"}),
				    Categories_RenamedColumns = Table.RenameColumns(Categories_RemovedOtherColumns,{{"Description", "L2"}}),
				    Categories_SplitL2 = Table.SplitColumn(Categories_RenamedColumns, "L2", Splitter.SplitTextByEachDelimiter({"("}, QuoteStyle.Csv, true), {"L2.Desc", "L2.Code"}),
				    Categories_RemoveRightParen = Table.ReplaceValue(Categories_SplitL2,")","",Replacer.ReplaceText,{"L2.Code"}),
				    Categories_MergeL2 = Table.CombineColumns(Categories_RemoveRightParen,{"L2.Code", "L2.Desc"},Combiner.CombineTextByDelimiter(": ", QuoteStyle.None),"L2"),
				    Categories_MergeForL1 = Table.NestedJoin(Categories_MergeL2, {"ParentDiagnosisCategory_ID"}, Categories_MergeL2, {"DiagnosisCategory_ID"}, "Category", JoinKind.Inner),
				    Categories_ExpandL1 = Table.ExpandTableColumn(Categories_MergeForL1, "Category", {"L2"}, {"L1"}),
				    Categories_RemovedColumns = Table.RemoveColumns(Categories_ExpandL1,{"ParentDiagnosisCategory_ID"}),
				    
				    //Combine
				    Combine_Merge = Table.NestedJoin(Codes_RemovedColumns, {"DiagnosisCategory_ID"}, Categories_RemovedColumns, {"DiagnosisCategory_ID"}, "Category", JoinKind.Inner),
				    Combine_Expand = Table.ExpandTableColumn(Combine_Merge, "Category", {"L2", "L1"}, {"L2", "L1"}),
				    Combine_RemovedColumns = Table.RemoveColumns(Combine_Expand,{"DiagnosisCategory_ID"}),
				    Combine_ReplacedValue = Table.ReplaceValue(Combine_RemovedColumns,null,each [L4],Replacer.ReplaceValue,{"L3"}),
				    Combine_ChangedType = Table.TransformColumnTypes(Combine_ReplacedValue,{{"L3", type text}}),
				    Combine_RemoveDot = Table.ReplaceValue(Combine_ChangedType,".","",Replacer.ReplaceText,{"ICD"}),
				    #"Replaced Value" = Table.ReplaceValue(Combine_RemoveDot,": Conditions of Uncertain Etiology","zzz: Conditions of Uncertain Etiology",Replacer.ReplaceText,{"L1"})
				in
				    #"Replaced Value"
				```

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

