table DX_Cases
	lineageTag: f6f202bf-6b1f-41ab-a2ba-784c5e49169f

	measure 'Total Cases PM Dx' =
			
			CALCULATE(
			    [Total Cases],
			    DX_Cases[DisplayOrder]=1,
			    DX_Cases[DiagnosisType]="MEDICAL"
			)
		formatString: #,0
		lineageTag: 95c0f8d6-e517-4f0e-bbcf-ae2e65237a5a

	measure 'Total Diagnoses from DX Table' = COUNTROWS(DX_Cases)
		lineageTag: 98746dca-d951-42e1-9763-36e87a478cbd

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total Cases M Dx' =
			
			CALCULATE(
			    [Total Cases],
			    DX_Cases[DiagnosisType]="MEDICAL"
			)
		formatString: #,0
		lineageTag: 816a6720-003e-47fc-8032-96d66ad28734

	measure 'Show only primary' = "Show only"
		lineageTag: c2890fa0-ec91-4489-bc8b-4f2db5af4536

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column PatientCase_ID
		formatString: 0
		lineageTag: 739931fa-8f01-4c68-9db1-a5f3c0af785c
		summarizeBy: none
		isNameInferred
		sourceColumn: StayCases[PatientCase_ID]

		annotation SummarizationSetBy = Automatic

	column DisplayOrder
		formatString: 0
		lineageTag: dbd5c036-00c5-4807-a8a8-0ee25c54a4db
		summarizeBy: sum
		isNameInferred
		sourceColumn: Diagnosis[DisplayOrder]

		annotation SummarizationSetBy = Automatic

	column L4
		lineageTag: dde7cccd-1b24-4dd8-97a1-3df2dda8c90e
		summarizeBy: none
		isNameInferred
		sourceColumn: DiagnosisCode[L4]

		annotation SummarizationSetBy = Automatic

	column L3
		lineageTag: 3c6fd47c-304f-48b9-bb30-7035adcdfad4
		summarizeBy: none
		isNameInferred
		sourceColumn: DiagnosisCode[L3]

		annotation SummarizationSetBy = Automatic

	column L2
		lineageTag: fd0edd47-ce22-418a-a94b-1772f4bc2f5e
		summarizeBy: none
		isNameInferred
		sourceColumn: DiagnosisCode[L2]

		annotation SummarizationSetBy = Automatic

	column L1
		lineageTag: 1da9408a-8cf8-45cd-8c5a-9742e1028cf9
		summarizeBy: none
		isNameInferred
		sourceColumn: DiagnosisCode[L1]

		annotation SummarizationSetBy = Automatic

	column DiagnosisType
		lineageTag: cb958671-036b-4a81-a4d4-5acc99019dbe
		summarizeBy: none
		isNameInferred
		sourceColumn: Diagnosis[DiagnosisType]

		annotation SummarizationSetBy = Automatic

	column Onset
		formatString: Short Date
		lineageTag: 1f559c71-a5c0-4120-b92e-281fbeeb35d3
		summarizeBy: none
		isNameInferred
		sourceColumn: [Onset]

		annotation SummarizationSetBy = Automatic

	column 'Dx Age' =
			
			DATEDIFF(
			    DX_Cases[Onset],
			    RELATED(StayCases[TherapyStartDate]),
			    DAY
			)
		formatString: 0
		lineageTag: 005f70f2-5e86-49b9-8777-ab6aaa009a87
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column ICD
		lineageTag: caad9794-a9dc-430b-8145-5ca506d473e2
		summarizeBy: none
		isNameInferred
		sourceColumn: DiagnosisCode[ICD]

		annotation SummarizationSetBy = Automatic

	column Type = ```
			
			// IF(DX_Cases[DisplayOrder]=1,"Primary","Secondary")
			
			VAR MinDisplayOrderForCase =
			    CALCULATE (
			        MIN ( DX_Cases[DisplayOrder] ),
			        ALLEXCEPT ( DX_Cases, DX_Cases[PatientCase_ID] )
			    )
			RETURN
			    IF ( DX_Cases[DisplayOrder] = MinDisplayOrderForCase, "Primary", "Secondary" )
			
			```
		lineageTag: ce550af3-0032-44b1-93a4-6157ba8cd4c8
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	/// Curated clinical condition grouping by ICD prefix. Activate a group by filtering
	/// this column (e.g. Stroke). Combine with DX_Cases[Type]="Primary" for primary-dx cohorts.
	/// Stroke = I60-I63 (hemorrhagic + ischemic) + I69 (sequelae); excludes I65-I68 (no infarction) + G45 (TIA).
	/// Add conditions by extending the SWITCH (e.g. Total Joint).
	column 'Condition Group' =
			
			SWITCH(
			    TRUE(),
			    LEFT(DX_Cases[ICD],3) IN {"I60","I61","I62","I63","I69"}, "Stroke",
			    BLANK()
			)
		lineageTag: 5acc0001-0000-4000-8000-000000000001
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition DX_Cases = calculated
		mode: import
		source =
				
				FILTER(
				    SUMMARIZE(
				        FILTER(Diagnosis,Diagnosis[DisplayOrder]<=100 && Diagnosis[DiagnosisType] IN {"MEDICAL"}),
				        StayCases[PatientCase_ID],
				        Diagnosis[DisplayOrder],
				        Diagnosis[DiagnosisType],
				        DiagnosisCode[L4],
				        DiagnosisCode[L3],
				        DiagnosisCode[L2],
				        DiagnosisCode[L1],
				        DiagnosisCode[ICD],
				        "Onset",MAX(Diagnosis[OnsetDate])
				    ),
				    ISBLANK(StayCases[PatientCase_ID])=FALSE()
				)

	annotation PBI_Id = 1d02769579db49cb821a747a2c4e86fa
