table Employees
	lineageTag: 05807a58-3a85-42cc-9afe-f00852e0d42a

	measure 'Total Therapists' = COUNTROWS(Employees)
		formatString: #,0
		lineageTag: 1f9fc776-56d6-44f6-8f0c-0a025d3f04f8

	measure 'Therapist List' =
			
			// IF(HASONEVALUE(StayCases[PatientCase_ID])=FALSE(),BLANK(),
			//     IF(
			//         ISINSCOPE(Service[Type]),
			//         CONCATENATEX(
			//             FILTER(VALUES(Treatments[TherapistLabel]),NOT(ISBLANK(Treatments[TherapistLabel]))),
			//             Treatments[TherapistLabel],
			//             ", ",
			//             [Total Minutes],
			//             DESC
			//         )
			//     )
			// )
			
			
			
			
			CONCATENATEX(
			    FILTER(VALUES(Treatments[TherapistLabel]),NOT(ISBLANK(Treatments[TherapistLabel]))),
			    Treatments[TherapistLabel],
			    ", ",
			    [Total Minutes],
			    DESC
			)
		lineageTag: 79f2b150-bd2f-4e87-9ed5-e6cb801ae347

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Therapist List 2' =
			
			// var evalTable = SUMMARIZE(FILTER(TreatmentsDetails,RELATED(Service[Type])="Eval"),Treatments[TherapistLabel],"Minutes",[Total Minutes])
			// var evalList = CONCATENATEX(evalTable,Treatments[TherapistLabel],", ",[Minutes],DESC)
			
			// var treatTable = SUMMARIZE(FILTER(TreatmentsDetails,RELATED(Service[Type])="Treat"),Treatments[TherapistLabel],"Minutes",[Total Minutes])
			// var treatList = CONCATENATEX(treatTable,Treatments[TherapistLabel],", ",[Minutes],DESC)
			
			// return
			// "𝗘𝘃𝗮𝗹: "&evalList&"; 𝗧𝗿𝗲𝗮𝘁: "&treatList
			
			
			
			var evalTable = SUMMARIZE(FILTER(TreatmentsDetails,RELATED(Service[Type])="Eval"),Treatments[TherapistLabel],"Minutes",[Total Minutes])
			var evalList = CONCATENATEX(evalTable,Treatments[TherapistLabel],", ",[Minutes],DESC)
			
			var treatTable = SUMMARIZE(FILTER(TreatmentsDetails,RELATED(Service[Type])="Treat"),Treatments[TherapistLabel],"Minutes",[Total Minutes])
			var treatList = CONCATENATEX(treatTable,Treatments[TherapistLabel],", ",[Minutes],DESC)
			
			return
			IF([Total Minutes]=0,BLANK(),
			"𝗘𝘃𝗮𝗹: "&evalList&"; 𝗧𝗿𝗲𝗮𝘁: "&treatList
			)
		lineageTag: dc760bd6-b1a7-47a5-bd62-bb8181ba4e05

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Person_ID
		dataType: int64
		isKey
		formatString: 0
		lineageTag: a0756802-bb89-4737-b448-7e513eb79d97
		summarizeBy: none
		sourceColumn: Person_ID

		annotation SummarizationSetBy = Automatic

	column Name
		dataType: string
		lineageTag: 86701224-536a-43d0-8b73-3e97d6b27c2b
		summarizeBy: none
		sourceColumn: Name

		annotation SummarizationSetBy = Automatic

	column StaffTitle
		dataType: string
		lineageTag: df851b25-78b4-461a-81f3-499c4decb1c2
		summarizeBy: none
		sourceColumn: StaffTitle

		annotation SummarizationSetBy = Automatic

	column 'Short Name'
		dataType: string
		lineageTag: 34d10083-98dc-46b6-99de-b75b36b41c9e
		summarizeBy: none
		sourceColumn: Short Name

		annotation SummarizationSetBy = Automatic

	column IsInactive
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: f1bab88e-f77b-4ecc-af64-6c779cb89784
		summarizeBy: none
		sourceColumn: IsInactive

		annotation SummarizationSetBy = Automatic

	column SupervisorPerson_ID
		dataType: int64
		formatString: 0
		lineageTag: fc547dc3-889c-45dd-bbc2-1576f600a20b
		summarizeBy: none
		sourceColumn: SupervisorPerson_ID

		annotation SummarizationSetBy = Automatic

	column Taxonomy_ID
		dataType: int64
		formatString: 0
		lineageTag: 3cfb98a8-9e0a-4380-9fd2-2be0202cd34b
		summarizeBy: none
		sourceColumn: Taxonomy_ID

		annotation SummarizationSetBy = Automatic

	column EmployeeNo
		dataType: string
		lineageTag: daef7094-0ddb-4e8b-9af4-474f316478a0
		summarizeBy: none
		sourceColumn: EmployeeNo

		annotation SummarizationSetBy = Automatic

	column 'Therapist Name'
		dataType: string
		lineageTag: 43f58bc9-c689-4401-9fcc-ea0b8fc12733
		summarizeBy: none
		sourceColumn: Therapist Name

		annotation SummarizationSetBy = Automatic

	column JobTitle
		dataType: string
		lineageTag: bc432d8f-a035-4ad4-8b27-eae5bb90f6c1
		summarizeBy: none
		sourceColumn: JobTitle

		annotation SummarizationSetBy = Automatic

	column Credentials
		dataType: string
		lineageTag: 64b9b580-0aaf-4d1c-b027-71fcfa0f429a
		summarizeBy: none
		sourceColumn: Credentials

		annotation SummarizationSetBy = Automatic

	column JobCodeId
		dataType: int64
		formatString: 0
		lineageTag: 8898ece1-44ac-46d2-97ae-2669230d3403
		summarizeBy: none
		sourceColumn: JobCodeId

		annotation SummarizationSetBy = Automatic

	column 'Therapist Label' = Employees[Therapist Name]&" ("&Employees[JobTitle]&")"
		lineageTag: c35bfe96-babf-4431-968d-6408045e260e
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition Employees = m
		mode: import
		queryGroup: People
		source =
				let
				    Source = Value.NativeQuery(_NetHealthBronze, "SELECT Person_ID, FirstName, LastName, StaffTitle, ISNULL(IsInactive,0) AS IsInactive, SupervisorPerson_ID, Taxonomy_ID FROM dbo.Person WHERE Person_ID IS NOT NULL"),
				    #"Added Custom Column" = Table.AddColumn(Source, "Short Name", each Text.Combine({Text.Start([FirstName], 1), " ", [LastName]}), type text),
				    #"Merged Columns" = Table.CombineColumns(#"Added Custom Column",{"FirstName", "LastName"},Combiner.CombineTextByDelimiter(" ", QuoteStyle.None),"Name"),
				    // --- folded-in Silver employee attributes (formerly EmployeeBasicInfo) ---
				    EmpInfo = Value.NativeQuery(_SilverSource, "SELECT NetHealthId AS Person_ID, EmployeeNumber AS EmployeeNo, FullName, JobTitle, Discipline AS Credentials, TRY_CAST(JobCode AS int) AS JobCodeId FROM (SELECT *, ROW_NUMBER() OVER (PARTITION BY NetHealthId ORDER BY SourceType, Username) AS rn FROM dbo.employee WHERE NetHealthId IS NOT NULL AND ISNULL(EmployeeNumber,'') <> '' AND EmployeeNumber <> '99999') x WHERE x.rn = 1"),
				    #"Renamed EmpInfo" = Table.RenameColumns(EmpInfo, {{"FullName", "Therapist Name"}}),
				    #"Joined EmpInfo" = Table.NestedJoin(#"Merged Columns", {"Person_ID"}, #"Renamed EmpInfo", {"Person_ID"}, "_e", JoinKind.LeftOuter),
				    #"Expanded EmpInfo" = Table.ExpandTableColumn(#"Joined EmpInfo", "_e", {"EmployeeNo", "Therapist Name", "JobTitle", "Credentials", "JobCodeId"}, {"EmployeeNo", "Therapist Name", "JobTitle", "Credentials", "JobCodeId"})
				in
				    #"Expanded EmpInfo"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

