table MeasureTable
	lineageTag: 81d3a9b3-47f2-40a4-a981-c24b4592eac3

	measure ALOS =
			
			DIVIDE(
			    [Total Days],
			    [Total Cases]
			)
		formatString: #,0.0
		displayFolder: ALOS
		lineageTag: 630298d4-6fa8-4095-a83c-c6e6f4033dbc

	measure DTC =
			
			DIVIDE(
			    CALCULATE([Total Cases],DischargeDestination[Group] = "Community"),
			    CALCULATE([Total Cases],DischargeDestination[Type] <> "Unknown")
			)
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: Discharge Destination
		lineageTag: c0c4a183-0f59-487e-b863-419b6f2a549c

	measure Rehosp =
			
			DIVIDE(
			    CALCULATE([Total Cases],FILTER(DischargeDestination,DischargeDestination[Setting] = "Hospital")),
			    CALCULATE([Total Cases],DischargeDestination[Type] <> "Unknown")
			)
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: Discharge Destination
		lineageTag: e558747b-e8ad-4732-88c7-26c7276228bf

	measure 'Total Units' = SUM(TreatmentsDetails[Units])
		formatString: #,0
		displayFolder: Units
		lineageTag: 041af93e-4596-43f7-be46-2b3b9acbf6ea

	measure 'Units per Visit (pt/ot)' =
			
			// IF([Total Cases All Payers]>0,
			// CALCULATE(
			//     DIVIDE(
			//         [Total Units],
			//         [Total Visits]
			//     ),
			//     Disciplines[Discipline] IN {"PT", "OT"}
			// ))
			
			CALCULATE(
			    DIVIDE(
			        [Total Units],
			        [Total Visits]
			    ),
			    Disciplines[Discipline] IN {"PT", "OT"}
			)
		formatString: 0.00
		displayFolder: Units
		lineageTag: 53b2f234-8bb4-425b-af53-c885887b0e79

	measure 'Minutes per Case' =
			
			DIVIDE(
			    [Total Minutes],
			    [Total Cases]
			)
		formatString: #,0
		displayFolder: Minutes
		lineageTag: 09ca9c98-9580-4994-8ccc-86a868cd0fb7

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Minutes per Code' = AVERAGE(TreatmentsDetails[Duration])
		displayFolder: Minutes
		lineageTag: 09b59067-ec3b-4429-81b1-6ee518c45303

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Minutes per Unit' = [Total Minutes]/[Total Units]
		displayFolder: Minutes
		lineageTag: d8c992c1-5536-4d67-a686-8e7550ad81ee

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Minutes per Visit' =
			
			DIVIDE(
			    [Total Minutes],
			    [Total Visits]
			)
		displayFolder: Minutes
		lineageTag: 7f234f4c-fab9-420d-88b0-43f471d3c32b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Minutes per Week' =
			
			DIVIDE(
			    [Total Minutes],
			    [Total Days]
			)*7
		formatString: #,0
		displayFolder: Minutes
		lineageTag: c69eb433-9ea3-4846-8162-e08312d65158

	measure 'Minutes Variance' =
			
			STDEVX.P(
			    KEEPFILTERS(VALUES(StayCases[PatientCase_ID])),
			    CALCULATE([Minutes per Week])
			)
		formatString: #,0
		displayFolder: Minutes
		lineageTag: d07b96eb-63ae-4cfc-9932-686dc4e7d7bf

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Total Minutes' = SUM(TreatmentsDetails[Duration])
		formatString: #,0
		displayFolder: Minutes
		lineageTag: 9150bd80-028f-4835-b56d-4f57923a42eb

	measure 'Total Days with Visits' = DISTINCTCOUNT(Treatments[CaseIDDate])
		formatString: #,0
		displayFolder: Visits
		lineageTag: 3736d65f-010b-4cef-b6a1-812476178245

	measure 'Total Visits' = COUNTROWS(Treatments)
		formatString: #,0
		displayFolder: Visits
		lineageTag: a7244d21-36e1-4319-a650-3808c07d4b02

	measure 'Visits per Discipline per Week' =
			
			// AVERAGEX(
			//     FILTER(StayCases,[Total Days]>=7),
			//     DIVIDE(
			//         DIVIDE(
			//             [Total Visits],
			//             [Total Days]
			//         )*7,
			//         [Total Disciplines]
			//     )
			// )
			
			// AVERAGEX(
			//     StayCases,
			//     DIVIDE(
			//         DIVIDE(
			//             [Total Visits],
			//             [Total Days]
			//         )*7,
			//         [Total Disciplines]
			//     )
			// )
			
			AVERAGEX(
			    StayCases,
			    DIVIDE(
			        [Visits per Week],
			        [Total Disciplines Unique]
			    )
			)
		formatString: 0.00
		displayFolder: Visits
		lineageTag: 2073f7b4-5040-4bbd-b36b-f70c5b1056e7

	measure 'Total Cases' =
			
			var v1 = COUNTROWS(StayCases)
			var v2 = CALCULATE(COUNTROWS(StayCases),FILTER(StayCases,[Total Tracks]>0))
			return v2
		formatString: #,0
		displayFolder: Cases
		lineageTag: 77a0d69a-1460-4d25-b7e1-774421d4d8a6

	measure 'Total Cases All Payers' =
			
			CALCULATE(
			    [Total Cases],
			    ALL(StayCases[Payer Categorization])
			)
		formatString: #,0
		displayFolder: Cases
		lineageTag: e10db99f-6d15-41b2-a2b8-31d29896fbce

	measure 'Drill Button Text' =
			
			IF(
			    HASONEVALUE(StayCases[PatientCase_ID])=FALSE(),
			    "<<Please select a single episode from the table below, and then click this button>>",
			    "Show details for "&SELECTEDVALUE(Patients[Patient Name])
			)
		displayFolder: Outcomes
		lineageTag: 20866bb4-7c4b-4705-bdff-9fddc4becd12

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '% Minutes Group Therapy' =
			
			DIVIDE(
			    [Total Minutes Group Therapy],
			    [Total Minutes]
			)
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: Group Therapy
		lineageTag: b7270072-775e-414d-870d-f9f955796237

	measure '% Minutes Group Therapy Text' =
			
			FORMAT(
			    [% Minutes Group Therapy]+0,
			    "0.0%"
			)
			&" group minutes"
		displayFolder: Group Therapy
		lineageTag: 23bb5e0a-9f90-459d-93d0-480e842bce98

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '% Visits Group Therapy' =
			
			DIVIDE(
			    [Total Visits Group Therapy],
			    [Total Visits]
			)
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: Group Therapy
		lineageTag: 0b055e89-10ca-4348-8df3-430284117bd5

	measure '% Minutes Modalities' =
			
			DIVIDE(
			    [Total Minutes Modalities],
			    [Total Minutes]
			)
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: Modalities
		lineageTag: 150e6b1a-2b17-4259-b7c4-cc9d464f9914

	measure '% Visits Modalities' =
			
			DIVIDE(
			    [Total Visits Modalities],
			    [Total Visits]
			)
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: Modalities
		lineageTag: 980309bb-2df9-4935-a24f-b3b827b5c438

	measure '% Minutes Aquatic' =
			
			DIVIDE(
			    [Total Minutes Aquatic],
			    [Total Minutes]
			)
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: Aquatic
		lineageTag: a7ed64f1-2aab-4fcf-9d1a-c6095f9ca25d

	measure '% Visits Aquatic' =
			
			DIVIDE(
			    [Total Visits Aquatic],
			    [Total Visits]
			)
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: Aquatic
		lineageTag: ee74d04f-9aa0-4fbb-b5ff-dd154bd485c9

	measure 'Total Units Aquatic' =
			
			CALCULATE(
			    [Total Units],
			    Service[Specialty]="Aquatic"
			)
		formatString: #,0
		displayFolder: Aquatic
		lineageTag: 20a478b4-2a06-4bb9-995d-a549db1d0537

	measure 'Total Visits Aquatic' =
			
			CALCULATE(
			    [Total Visits],
			    Service[Specialty]="Aquatic"
			)
		formatString: #,0
		displayFolder: Aquatic
		lineageTag: 09f984a6-c6d0-4514-b19d-e5238dd3bdf0

	measure 'Gap: Stay to Case' =
			
			AVERAGEX(
			    StayCases,
			    DATEDIFF(RELATED(PatientStays[AdmitDate]),StayCases[TherapyStartDate],DAY)
			)
		displayFolder: Misc
		lineageTag: d4ef0e71-eaa1-4cf0-9a21-bd5dbe92042c

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Day 1 Evals' =
			
			var numerator = CALCULATE([Total Cases],FILTER(StayCases,[Gap: Stay to Case]=0))
			var denominator = [Total Cases]
			return DIVIDE(numerator,denominator)
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: Misc
		lineageTag: fdf9e2eb-60ee-439a-ae84-1987cf722c0c

	measure 'Disciplines Involved' =
			
			var VisitsPT = IF(CALCULATE([Total Visits],Disciplines[Discipline]="PT")>0,"PT")
			var VisitsOT = IF(CALCULATE([Total Visits],Disciplines[Discipline]="OT")>0,"OT")
			var VisitsST = IF(CALCULATE([Total Visits],Disciplines[Discipline]="ST")>0,"ST")
			var ValuesTable = FILTER({VisitsPT, VisitsOT, VisitsST}, NOT(ISBLANK([Value])))
			var ValuesList = CONCATENATEX(ValuesTable,[Value],"/")
			return ValuesList
		displayFolder: Misc
		lineageTag: 35288c9d-f2a5-4f80-880b-b642bb83bd14

		extendedProperty MeasureTemplate =
				{
				  "version": 0,
				  "daxTemplateName": "ConcatenateValues"
				}

		changedProperty = FormatString

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total Days' =
			
			// SUMX (
			//     VALUES(StayCases[PatientCase_ID]),
			//     CALCULATE (
			//         COUNTROWS (
			//             FILTER (
			//                 ALL('Calendar'),
			//                 COUNTROWS (
			//                     FILTER (
			//                         CaseTracks,
			//                         CaseTracks[PatientCase_ID] = MAX(StayCases[PatientCase_ID])
			//                         && 'Calendar'[Date] >= CaseTracks[StartDate]
			//                         && 'Calendar'[Date] <= CaseTracks[EndDate]
			//                     )
			//                 ) > 0
			//             )
			//         )
			//     )
			// )
			
			SUM(StayCases[UniqueDays])
			
			// SUMX(
			//     VALUES(StayCases[PatientCase_ID]),
			//     [Total Unique CaseTrackDays]
			// )
		formatString: #,0
		displayFolder: Misc
		lineageTag: e577077a-991e-4e07-aa63-8f4d448220d1

	measure 'Total Disciplines Unique' =
			
			CALCULATE(
			    DISTINCTCOUNT(Disciplines[Discipline]),
			    FILTER(
			        CaseTracks,
			        [Total Visits]>0
			    )
			)
		formatString: 0
		displayFolder: Misc
		lineageTag: 30637786-6920-4722-9f4a-0c59fc87f64c

	measure 'Total Minutes Modalities' =
			
			CALCULATE(
			    [Total Minutes],
			    Service[Specialty]="Modality"
			)
		formatString: #,0
		displayFolder: Modalities
		lineageTag: bb0e3b1a-7683-40bb-ac32-a0e0e77683e6

	measure 'Total Visits Modalities' =
			
			CALCULATE(
			    [Total Visits],
			    Service[Specialty]="Modality"
			)
		formatString: #,0
		displayFolder: Modalities
		lineageTag: 0beb139e-54f6-4ba2-b9e1-fdf5d3e7c78b

	measure 'Total Minutes Aquatic' =
			
			CALCULATE(
			    [Total Minutes],
			    Service[Specialty]="Aquatic"
			)
		formatString: #,0
		displayFolder: Aquatic
		lineageTag: 6596c2c5-da48-4ccf-9c49-022a36a1ced3

	measure 'Total Minutes Group Therapy' =
			
			CALCULATE(
			    [Total Minutes],
			    Service[Specialty]="Group"
			)
		formatString: #,0
		displayFolder: Group Therapy
		lineageTag: a143ce6d-d146-4894-8456-e9eb63a753d9

	measure 'Total Visits Group Therapy' =
			
			CALCULATE(
			    [Total Visits],
			    Service[Specialty]="Group"
			)
		formatString: #,0
		displayFolder: Group Therapy
		lineageTag: bd74514f-6473-4201-a20d-a04be32f0c04

	measure 'Total Units Modalities' =
			
			CALCULATE(
			    [Total Units],
			    Service[Specialty]="Modality"
			)
		formatString: #,0
		displayFolder: Modalities
		lineageTag: 2d661b13-a9b3-4151-915f-6970666e003b

	measure 'Total Units Group Therapy' =
			
			CALCULATE(
			    [Total Units],
			    Service[Specialty]="Group"
			)
		formatString: #,0
		displayFolder: Group Therapy
		lineageTag: 85b064db-d923-4f20-941a-6b5868892ffa

	measure 'Visits per Case' =
			
			DIVIDE(
			    [Total Visits],
			    [Total Cases]
			)
		formatString: 0.0
		displayFolder: Visits
		lineageTag: ab38a2fc-ed64-4890-89c6-49bce949f092

	measure 'Average Caseload' =
			
			DIVIDE(
			    [Total Days],
			    [Total Calendar Days]
			)
		displayFolder: Cases
		lineageTag: cf7a006a-84c0-4942-b315-e0fbd8dea458

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '% Assistant Minutes' =
			
			DIVIDE(
			    CALCULATE([Total Minutes],Treatments[AssistantModifier]=TRUE()),
			    [Total Minutes]
			)
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: Minutes
		lineageTag: 9f0f0498-5768-4290-a52f-53f42042d5f7

	measure 'Total Visits ST' = CALCULATE([Total Visits],Disciplines[Discipline]="ST")
		displayFolder: Visits
		lineageTag: 803ca051-dad9-454c-92be-64fcf3e086cc

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Rehosp Numerator' =
			
			CALCULATE(
			    [Total Cases],
			    DischargeDestination[Setting]="Hospital"
			)
		formatString: #,0
		displayFolder: Discharge Destination
		lineageTag: 37f26861-54c1-4227-925e-6a51a308d657

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Min Level to Go Home' = .7
		lineageTag: 28de03ef-77ac-4449-961e-74e6898953f6

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Minutes per Discipline per Week' =
			
			AVERAGEX(
			    StayCases,
			    DIVIDE(
			        DIVIDE(
			            [Total Minutes],
			            [Total Days]
			        )*7,
			        [Total Disciplines Unique]
			    )
			)
		displayFolder: Minutes
		lineageTag: 665da78d-22c3-4e62-ad0b-35e7e9d5a554

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Visits per Week' =
			
			DIVIDE(
			    [Total Visits],
			    [Total Days]
			)*7
		formatString: 0.00
		displayFolder: Visits
		lineageTag: 5396f10d-927c-45d4-a969-3bcd33632dd7

	measure 'ActiveFilters: Payer' =
			
			// IF(
			//     ISFILTERED('Payer Buckets'[Payer Categorization]),
			//     CONCATENATEX(VALUES('Payer Buckets'[Payer Categorization]),'Payer Buckets'[Payer Categorization],", "),
			//     IF(
			//         ISFILTERED('Payer Buckets'[Payer Grouping]),
			//         CONCATENATEX(VALUES('Payer Buckets'[Payer Grouping]),'Payer Buckets'[Payer Grouping],", "),
			//         "All"
			//     )
			// )
			
			IF(
			    ISFILTERED('Payer Buckets'[Payer Categorization]),
			    CONCATENATEX(VALUES('Payer Buckets'[Payer Categorization]),'Payer Buckets'[Payer Categorization],", "),
			    IF(
			        ISFILTERED('Payer Buckets'[Payer Grouping]),
			        CONCATENATEX(VALUES('Payer Buckets'[Payer Grouping]),'Payer Buckets'[Payer Grouping],", "),
			        "All"
			    )
			)
		lineageTag: e7eaa42f-8ad2-4237-a916-977ada3bd203

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'ActiveFilters: Discharge Destination' = ```
			
			// IF(
			//     ISFILTERED(DischargeDestination[Setting]),
			//     CONCATENATEX(VALUES(DischargeDestination[Setting]),DischargeDestination[Setting],", "),
			//     IF(
			//         ISFILTERED(DischargeDestination[Group]),
			//         CONCATENATEX(VALUES(DischargeDestination[Group]),DischargeDestination[Group],", "),
			//         "All"
			//     )
			// )
			
			var filteredExpected = 
			IF(
			    ISFILTERED(StayCases[Expected Discharge Destination]),
			    "Expected: "&CONCATENATEX(VALUES(StayCases[Expected Discharge Destination]),StayCases[Expected Discharge Destination],", ")
			)
			
			var filteredActual = 
			IF(
			    ISFILTERED(DischargeDestination[Setting]),
			    "Actual: "&CONCATENATEX(VALUES(DischargeDestination[Setting]),DischargeDestination[Setting],", "),
			    IF(
			        ISFILTERED(DischargeDestination[Group]),
			        "Actual: "&CONCATENATEX(VALUES(DischargeDestination[Group]),DischargeDestination[Group],", ")
			    )
			)
			
			var newline = UNICHAR(13)&UNICHAR(10)
			VAR multiline = REPT(newline,2)
			var concatTable = FILTER({filteredExpected, filteredActual}, NOT(ISBLANK([Value])))
			// return concatTable
			return COALESCE(CONCATENATEX(concatTable,[Value],newline),"All")
			```
		lineageTag: 30ff543f-1b0f-408a-ab59-b663870d42c8

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'ActiveFilters: Diagnosis' = ```
			
			// IF(
			//     ISFILTERED(DX_Cases[L4]),
			//     CONCATENATEX(VALUES(DX_Cases[L4]),DX_Cases[L4],", "),
			//     IF(
			//         ISFILTERED(DX_Cases[L3]),
			//         CONCATENATEX(VALUES(DX_Cases[L3]),DX_Cases[L3],", "),
			//         IF(
			//             ISFILTERED(DX_Cases[L2]),
			//             CONCATENATEX(VALUES(DX_Cases[L2]),DX_Cases[L2],", "),
			//             IF(
			//                 ISFILTERED(DX_Cases[L1]),
			//                 CONCATENATEX(VALUES(DX_Cases[L1]),DX_Cases[L1],", "),
			//                 "All"
			//             )
			//         )
			//     )
			// )
			
			var L4filter = ISFILTERED(DX_Cases[L4])
			var L3filter = ISFILTERED(DX_Cases[L3])
			var L2filter = ISFILTERED(DX_Cases[L2])
			var L1filter = ISFILTERED(DX_Cases[L1])
			var primary = ISFILTERED(DX_Cases[Type])
			var specificity = SWITCH(TRUE(),L4filter,4,L3filter,3,L2filter,2,L1filter,1,0)
			var note = 
			    SWITCH(
			        specificity,
			        4,CONCATENATEX(VALUES(DX_Cases[L4]),DX_Cases[L4],", "),
			        3,CONCATENATEX(VALUES(DX_Cases[L3]),DX_Cases[L3],", "),
			        2,CONCATENATEX(VALUES(DX_Cases[L2]),DX_Cases[L2],", "),
			        1,CONCATENATEX(VALUES(DX_Cases[L1]),DX_Cases[L1],", "),
			        "All"
			    )
			return note
			```
		lineageTag: e76bd4fb-6400-43f9-82a2-9673e4444f9b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'ActiveFilters: Discharge Type' =
			
			IF(
			    ISFILTERED(DischargeDestination[Type]),
			    CONCATENATEX(VALUES(DischargeDestination[Type]),DischargeDestination[Type],", "),
			    "All"
			)
		lineageTag: 90eea763-f824-42ed-bc64-e9140881e115

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'ActiveFilters: Place of Service' =
			
			IF(
			    ISFILTERED(IntakeSources[Name]),
			    CONCATENATEX(VALUES(IntakeSources[Name]),IntakeSources[Name],", "),
			    IF(
			        ISFILTERED(IntakeSources[SourceType]),
			        CONCATENATEX(VALUES(IntakeSources[SourceType]),IntakeSources[SourceType],", "),
			        "All"
			    )
			)
		lineageTag: 767eebd5-a157-4979-8d5a-8478900b3684

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'ActiveFilters: All' = ```
			
			var newline = UNICHAR(13)&UNICHAR(10)
			var multiline = REPT(newline,2)
			
			var payer = 
			IF(ISFILTERED('Payer Buckets'[Payer Categorization]) || ISFILTERED('Payer Buckets'[Payer Grouping]),"Payer:"&newline&
			SWITCH(
			    TRUE(),
			    ISFILTERED('Payer Buckets'[Payer Categorization]),CONCATENATEX(VALUES('Payer Buckets'[PCLabel]),'Payer Buckets'[PCLabel],", "),
			    ISFILTERED('Payer Buckets'[Payer Grouping]),CONCATENATEX(VALUES('Payer Buckets'[PGLabel]),'Payer Buckets'[PGLabel],", ")
			))
			
			var agerange = 
			IF(ISFILTERED(StayCases[Age Range]),"Age Range:"&newline&
			CONCATENATEX(VALUES(StayCases[Age Range]),StayCases[Age Range],", ")
			)
			
			var diagnosis = 
			IF(NOT(ISFILTERED(DX_Cases[L1]) || ISFILTERED(DX_Cases[L2]) || ISFILTERED(DX_Cases[L3]) || ISFILTERED(DX_Cases[L4])),BLANK(),
			IF(ISFILTERED(DX_Cases[Type]),SELECTEDVALUE(DX_Cases[Type])&" ")&
			"Diagnosis:"&newline&
			SWITCH(
			    TRUE(),
			    ISFILTERED(DX_Cases[L4]),CONCATENATEX(VALUES(DX_Cases[L4]),DX_Cases[L4],", "),
			    ISFILTERED(DX_Cases[L3]),CONCATENATEX(VALUES(DX_Cases[L3]),DX_Cases[L3],", "),
			    ISFILTERED(DX_Cases[L2]),CONCATENATEX(VALUES(DX_Cases[L2]),DX_Cases[L2],", "),
			    ISFILTERED(DX_Cases[L1]),CONCATENATEX(VALUES(DX_Cases[L1]),DX_Cases[L1],", ")
			))
			
			var DCtype = 
			IF(ISFILTERED(DischargeDestination[Type]),"D/C Type"&newline&
			CONCATENATEX(VALUES(DischargeDestination[Type]),DischargeDestination[Type],", ")
			)
			
			var DCdest = 
			IF(ISFILTERED(DischargeDestination[Setting]) || ISFILTERED(DischargeDestination[Group]),"D/C Destination"&newline&
			SWITCH(
			    TRUE(),
			    ISFILTERED(DischargeDestination[Setting]),CONCATENATEX(VALUES(DischargeDestination[Setting]),DischargeDestination[Setting],", "),
			    ISFILTERED(DischargeDestination[Group]),CONCATENATEX(VALUES(DischargeDestination[Group]),DischargeDestination[Group],", ")
			))
			
			var DCexpected = 
			IF(ISFILTERED(StayCases[Expected Discharge Destination]),"Expected D/C Destination:"&newline&
			CONCATENATEX(VALUES(StayCases[Expected Discharge Destination]),StayCases[Expected Discharge Destination],", ")
			)
			
			var placeofservice = 
			IF(ISFILTERED(IntakeSources[Name]) || ISFILTERED(IntakeSources[SourceType]),"Place of Service:"&newline&
			SWITCH(
			    TRUE(),
			    ISFILTERED(IntakeSources[Name]),CONCATENATEX(VALUES(IntakeSources[Name]),IntakeSources[Name],", "),
			    ISFILTERED(IntakeSources[SourceType]),CONCATENATEX(VALUES(IntakeSources[SourceType]),IntakeSources[SourceType],", ")
			))
			
			var concatTable = FILTER({payer,agerange,diagnosis,DCtype,DCdest,DCexpected,placeofservice},NOT(ISBLANK([Value])))
			
			return COALESCE(CONCATENATEX(concatTable,[Value],multiline),"None")
			```
		lineageTag: b41204bb-02ef-4f3f-a782-b080312ebfff

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Outcome 100%' = 1
		lineageTag: 8876e302-51a2-4920-92ca-f0cc45c0d88d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Benchmark Subtitle' = BLANK()
		displayFolder: Cases
		lineageTag: c493201c-99e0-4151-b0cd-8f08f98a5342

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Outcome 150%' = 1.10
		lineageTag: 0155494f-a6b5-4913-94fc-b44fe938854a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Discharge Level Label' = "D/C"
		displayFolder: Outcomes
		lineageTag: cf51246b-5156-469f-8ac7-ef2c8a7ec931

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Outcome 200%' =
			
			1.5
			// MAXX(ALL(BenchmarkTable),[Outcome 150% + Gain])*1.12
		lineageTag: 4dae9b4d-385a-46ab-99af-49ed074b920f

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Zero = 0
		lineageTag: 9806c903-6b11-4b72-a2b0-0b06aefc5285

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total Cases %' =
			
			var numerator = [Total Cases]
			var denominator = CALCULATE([Total Cases],ALLSELECTED(StayCases))
			var ratio = DIVIDE(numerator,denominator)
			return ratio
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: Cases
		lineageTag: a29d587f-325b-45bf-a73b-c2883946ca75

	measure 'Total Cases % (improved)' =
			
			var numerator = [Total Cases]
			var denominator = CALCULATE([Total Cases],ALLSELECTED(StayCases))
			var ratio = DIVIDE(numerator,denominator)
			return IF(SELECTEDVALUE(StayCases[Case Result])="Improved",ratio)
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: Cases
		lineageTag: b02b787a-490a-44b5-9a39-dc406ef5872e

	measure 'Total Cases % (not improved)' =
			
			var numerator = [Total Cases]
			var denominator = CALCULATE([Total Cases],ALLSELECTED(StayCases))
			var ratio = DIVIDE(numerator,denominator)
			return IF(SELECTEDVALUE(StayCases[Case Result])<>"Improved",ratio)
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: Cases
		lineageTag: 17d345f8-8abe-497e-9095-3c484d422d6a

	measure 'Results Distribution Subtitle' =
			
			var casesincluded = [Total Cases] //because visual will be filtered to exclude N/A's
			var casestotal = CALCULATE([Total Cases],REMOVEFILTERS(StayCases[Case Result]))
			var casesexcluded = casestotal-casesincluded+0
			return
			"Includes "&FORMAT(casesincluded,"#,###")&" of the total "&FORMAT(casestotal,"#,###")&" discharges (excludes "&FORMAT(casesexcluded,"#,##0")&" without valid outcomes)"
		displayFolder: Cases
		lineageTag: 37efb285-3cdd-4d85-9faf-febb63a336c2

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'ActiveFilters: State' =
			
			IF(
			    ISFILTERED(Facility[State]),
			    CONCATENATEX(VALUES(Facility[State]),Facility[State],", "),
			    "All"
			)
		lineageTag: 612541c1-b846-48e4-b575-b2a6fc542bbf

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Patient Acuity Delta Image Higher' =
			
			"data:image/svg+xml;utf8,<svg width=""24"" height=""24"" viewBox=""0 0 24 24"" fill=""none"" xmlns=""http://www.w3.org/2000/svg"">
			<path d=""M7.625 11.1667L12 7M12 7L16.375 11.1667M12 7L12 17"" stroke=""#9EB4C3"" stroke-width=""2"" stroke-linecap=""round"" stroke-linejoin=""round""/>
			</svg>"
		lineageTag: f0504686-972b-4fd0-8c08-b73f1d9427fd
		dataCategory: ImageUrl

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Patient Acuity Delta Image Lower' =
			
			"data:image/svg+xml;utf8,<svg width=""24"" height=""24"" viewBox=""0 0 24 24"" fill=""none"" xmlns=""http://www.w3.org/2000/svg"">
			<path d=""M16.375 12.8333L12 17M12 17L7.625 12.8333M12 17L12 7"" stroke=""#9EB4C3"" stroke-width=""2"" stroke-linecap=""round"" stroke-linejoin=""round""/>
			</svg>"
		lineageTag: e7715d33-536e-434b-80e4-ae7c26fa9af6
		dataCategory: ImageUrl

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Outcomes Delta Image Good' =
			
			// "data:image/svg+xml;utf8,<svg width=""24"" height=""24"" viewBox=""0 0 24 24"" fill=""none"" xmlns=""http://www.w3.org/2000/svg"">
			// <circle cx=""12"" cy=""12"" r=""12"" fill=""#0C436A"" fill-opacity=""1.00""/>
			// </svg>"
			
			"data:image/svg+xml;utf8,<svg width=""24"" height=""24"" viewBox=""0 0 24 24"" fill=""none"" xmlns=""http://www.w3.org/2000/svg"">
			<path d=""M9.54961 18L3.84961 12.3L5.27461 10.875L9.54961 15.15L18.7246 5.97498L20.1496 7.39998L9.54961 18Z"" fill=""#1D1B20"" stroke=""#0C436A"" stroke-width=""1"" stroke-linecap=""round"" stroke-linejoin=""round""/>
			</svg>"
		displayFolder: Outcomes
		lineageTag: 71bcbb90-e114-4aef-bd02-cf6a5fad0e04
		dataCategory: ImageUrl

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Outcomes Delta Image Bad' =
			
			// "data:image/svg+xml;utf8,<svg width=""24"" height=""24"" viewBox=""0 0 24 24"" fill=""none"" xmlns=""http://www.w3.org/2000/svg"">
			// <circle cx=""12"" cy=""12"" r=""12"" fill=""#9EB4C3""  fill-opacity=""1.00""/>
			// </svg>"
			
			"data:image/svg+xml;utf8,<svg width=""24"" height=""24"" viewBox=""0 0 24 24"" fill=""none"" xmlns=""http://www.w3.org/2000/svg"">
			<path d=""M18 6L6 18M6 6L18 18"" stroke=""#9EB4C3"" stroke-width=""4"" stroke-linecap=""round"" stroke-linejoin=""round""/>
			</svg>"
		displayFolder: Outcomes
		lineageTag: 2e489efd-ff41-445d-aa62-46b78817ad7d
		dataCategory: ImageUrl

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Benchmark Reference Label' =
			
			"Benchmark"
			// "Baseline"
			// IF(ISFILTERED('BM Chain'[Name])=FALSE(),"Aegis Avg","Chain Avg")
			
			// IF(ISFILTERED('Override Chain'[Name]),"Chain avg",
			// IF(ISFILTERED('Override State'[BillingState]),SELECTEDVALUE('Override State'[BillingState])&" avg",
			// IF(ISFILTERED('Override Type'[Type]),SELECTEDVALUE('Override Type'[Type])&" avg",
			// "Aegis avg"
			// )))
		displayFolder: Cases
		lineageTag: 3c67df62-77c3-4461-87c0-f4c26ccd8639

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'ActiveFilters: Diagnosis Header' =
			
			// "Diagnosis"&
			// IF(
			//     ISFILTERED(DX_Cases[Type]),
			//     " (primary)"
			// )
			
			"Diagnosis"&
			IF(ISFILTERED(DX_Cases[Type])=FALSE(),BLANK(),
			SWITCH(
			    SELECTEDVALUE(DX_Cases[Type]),
			    "Primary"," (pri)",
			    "Secondary"," (sec)"
			))
		lineageTag: f6cfda3f-7c4e-4acc-959b-abcdc45cfb97

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total Minutes All Therapists' =
			
			// CALCULATE(
			//     [Total Minutes],
			//     ALL(EmployeeBasicInfo[Therapist Name])
			// )
			
			// CALCULATE(
			//     [Total Minutes],
			//     ALL(EmployeeBasicInfo[Therapist Name]),
			//     ALL(Disciplines),
			//     FILTER(
			//         StayCases,
			//         [Total Minutes]>0
			//     )
			// )
			
			// CALCULATE(
			//     [Total Minutes],
			//     ALL(EmployeeBasicInfo),
			//     ALL(Disciplines),
			//     FILTER(
			//         StayCases,
			//         [Total Minutes]>0
			//     )
			// )
			
			// CALCULATE(
			//     [Total Minutes],
			//     FILTER(
			//         ALL(Treatments),
			//         RELATED(Disciplines[Discipline])=SELECTEDVALUE(Disciplines[Discipline])
			//     ),
			//     FILTER(
			//         StayCases,
			//         [Total Minutes]>0
			//     )
			// )
			
			var FilteredCases = VALUES(StayCases[PatientCase_ID])
			var FilteredDisciplines = VALUES(Disciplines[Discipline])
			
			return
			CALCULATE(
			    [Total Minutes],
			    StayCases[PatientCase_ID] IN FilteredCases,
			    FILTER(
			        ALL(Treatments),
			        RELATED(Disciplines[Discipline]) IN FilteredDisciplines
			    )
			)
		formatString: #,0
		lineageTag: 95754d9c-4545-4688-8dab-8e9811643744

	measure 'Total Minutes % Delivered by Therapist' =
			
			DIVIDE(
			    [Total Minutes],
			    [Total Minutes All Therapists]
			)
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: 9fde75a2-4980-4d5c-9962-a27b3bdf0715

	measure 'Total Minutes Eval' =
			
			CALCULATE(
			    [Total Minutes],
			    Service[Type]="EVAL"
			)
		formatString: #,0
		lineageTag: ff58530c-d9ff-4f8a-aeb4-5613dd00b636

	measure 'Total Visits Eval' =
			
			CALCULATE(
			    [Total Visits],
			    Service[Type]="EVAL"
			)
		lineageTag: 4eabb288-447c-4f7b-9e77-bb29cac9dade

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total Disciplines Added' =
			
			// CALCULATE(
			//     DISTINCTCOUNT(Disciplines[Discipline]),
			//     FILTER(
			//         CaseTracks,
			//         [Total Visits]>0
			//     )
			// )
			
			SUMX(
			    StayCases,
			    [Total Disciplines Unique]
			)
		formatString: #,0
		displayFolder: Misc
		lineageTag: d1e0fe29-9294-4dc2-a168-8247bcfe6f28

	measure 'Total Minutes Eval All Therapists' =
			
			// CALCULATE(
			//     [Total Minutes Eval],
			//     ALL(EmployeeBasicInfo),
			//     ALL(Disciplines),
			//     FILTER(
			//         StayCases,
			//         [Total Minutes Eval]>0
			//     )
			// )
			
			// CALCULATE(
			//     [Total Minutes Eval],
			//     FILTER(
			//         ALL(Treatments),
			//         RELATED(Disciplines[Discipline])=SELECTEDVALUE(Disciplines[Discipline])
			//     ),
			//     FILTER(
			//         StayCases,
			//         [Total Minutes]>0
			//     )
			// )
			
			// CALCULATE(
			//     [Total Minutes All Therapists],
			//     Service[Type]="EVAL"
			// )
			
			var FilteredCases = VALUES(StayCases[PatientCase_ID])
			var FilteredDisciplines = VALUES(Disciplines[Discipline])
			
			return
			CALCULATE(
			    [Total Minutes Eval],
			    StayCases[PatientCase_ID] IN FilteredCases,
			    FILTER(
			        ALL(Treatments),
			        RELATED(Disciplines[Discipline]) IN FilteredDisciplines
			    )
			)
		formatString: #,0
		lineageTag: 0168226a-fb47-4107-9d46-7be2cb0ff19c

	measure 'Total Minutes Eval % Delivered by Therapist' =
			
			DIVIDE(
			    [Total Minutes Eval],
			    [Total Minutes Eval All Therapists]
			)
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: 47e19ca1-0022-4ebf-bc2e-dfd6649178ee

	measure 'Total Minutes Treat' =
			
			CALCULATE(
			    [Total Minutes],
			    Service[Type]="TREAT"
			)
		formatString: #,0
		lineageTag: 6ab2fb6d-42f8-4982-8944-31d51163a85b

	measure 'Total Minutes Treat All Therapists' =
			
			// CALCULATE(
			//     [Total Minutes Treat],
			//     ALL(EmployeeBasicInfo),
			//     ALL(Disciplines),
			//     FILTER(
			//         StayCases,
			//         [Total Minutes Treat]>0
			//     )
			// )
			
			// CALCULATE(
			//     [Total Minutes Treat],
			//     FILTER(
			//         ALL(Treatments),
			//         RELATED(Disciplines[Discipline])=SELECTEDVALUE(Disciplines[Discipline])
			//     ),
			//     FILTER(
			//         StayCases,
			//         [Total Minutes]>0
			//     )
			// )
			
			// CALCULATE(
			//     [Total Minutes All Therapists],
			//     Service[Type]="TREAT"
			// )
			
			var FilteredCases = VALUES(StayCases[PatientCase_ID])
			var FilteredDisciplines = VALUES(Disciplines[Discipline])
			
			return
			CALCULATE(
			    [Total Minutes Treat],
			    StayCases[PatientCase_ID] IN FilteredCases,
			    FILTER(
			        ALL(Treatments),
			        RELATED(Disciplines[Discipline]) IN FilteredDisciplines
			    )
			)
		formatString: #,0
		lineageTag: 1a824b15-0276-4731-b6f7-245a0779e18f

	measure 'Total Minutes Treat % Delivered by Therapist' =
			
			DIVIDE(
			    [Total Minutes Treat],
			    [Total Minutes Treat All Therapists]
			)
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: 28b8e052-8293-421a-9c29-6550f80a441c

	measure 'ActiveFilters: Age Range' =
			
			IF(
			    ISFILTERED(StayCases[Age Range]),
			    CONCATENATEX(VALUES(StayCases[Age Range]),StayCases[Age Range],", "),
			    "All"
			)
		lineageTag: fb164b2d-05a2-40c9-aed1-1050dc373182

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total Minutes Skilled Maintenance' =
			
			CALCULATE(
			    [Total Minutes],
			    Service[ServiceCode]="SkldM"
			)
		formatString: #,0
		lineageTag: f20909ed-8877-40ee-b764-0149c4ac419c

	measure 'Total Cases % Complement' = 1-[Total Cases %]
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: Cases
		lineageTag: f25fc684-d4a5-4847-a9ae-80ee527ff73d

	measure 'ActiveFilters: Override' =
			
			var newline = UNICHAR(13)&UNICHAR(10)
			
			var overridedivision = IF(ISFILTERED(Facility[Division]),"Division(s): "&CONCATENATEX(VALUES(Facility[Division]),Facility[Division],", "))
			var concatTable = FILTER({overridedivision},NOT(ISBLANK([Value])))
			return CONCATENATEX(concatTable,[Value],newline)
		lineageTag: 84aa1836-d8ee-4bb0-a2cd-3adaaf948954

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'ActiveFilters: D/C Status' = ```
			
			var newline = UNICHAR(13)&UNICHAR(10)
			var multiline = REPT(newline,2)
			
			var DCtype = 
			IF(ISFILTERED(DischargeDestination[Type]),"Type:"&" "&
			CONCATENATEX(VALUES(DischargeDestination[Type]),DischargeDestination[Type],", ")
			)
			
			var DCexpected = 
			IF(ISFILTERED(StayCases[Expected Discharge Destination]),"Expected:"&" "&
			CONCATENATEX(VALUES(StayCases[Expected Discharge Destination]),StayCases[Expected Discharge Destination],", ")
			)
			
			var DCdest = 
			IF(ISFILTERED(DischargeDestination[Setting]) || ISFILTERED(DischargeDestination[Group]),"Actual: "&" "&
			SWITCH(
			    TRUE(),
			    ISFILTERED(DischargeDestination[Setting]),CONCATENATEX(VALUES(DischargeDestination[Setting]),DischargeDestination[Setting],", "),
			    ISFILTERED(DischargeDestination[Group]),CONCATENATEX(VALUES(DischargeDestination[Group]),DischargeDestination[Group],", ")
			))
			
			var concatTable = FILTER({DCtype,DCexpected,DCdest},NOT(ISBLANK([Value])))
			
			return COALESCE(CONCATENATEX(concatTable,[Value],newline),"All")
			```
		lineageTag: b8921e2b-f799-4a28-ad4a-daafa247d3b7

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'ActiveFilters: Patient' = ```
			
			var newline = UNICHAR(13)&UNICHAR(10)
			var multiline = REPT(newline,2)
			
			var payer = 
			IF(
			    ISFILTERED('Payer Buckets'[Payer Categorization]) || ISFILTERED('Payer Buckets'[Payer Grouping]) || ISFILTERED(Payers[Name]),
			    "Payer:" & " " &
			    // Add categorization or grouping label
			    SWITCH(
			        TRUE(),
			        ISFILTERED('Payer Buckets'[Payer Categorization]),
			            CONCATENATEX(VALUES('Payer Buckets'[PCLabel]), 'Payer Buckets'[PCLabel], ", "),
			        ISFILTERED('Payer Buckets'[Payer Grouping]),
			            CONCATENATEX(VALUES('Payer Buckets'[PGLabel]), 'Payer Buckets'[PGLabel], ", ")
			    ) &
			    // Add separator if both payer segment and name are filtered
			    IF(
			        (ISFILTERED('Payer Buckets'[Payer Categorization]) || ISFILTERED('Payer Buckets'[Payer Grouping])) 
			        && ISFILTERED(Payers[Name]),
			        " | ",
			        ""
			    ) &
			    // Append payer name if filtered
			    IF(
			        ISFILTERED(Payers[Name]),
			        CONCATENATEX(VALUES(Payers[Name]), Payers[Name], ", ")
			    )
			)
			
			var agerange = 
			IF(ISFILTERED(StayCases[Age Range]),"Age Range:"&" "&
			CONCATENATEX(VALUES(StayCases[Age Range]),StayCases[Age Range],", ")
			)
			
			var placeofresidence = 
			IF(ISFILTERED(IntakeSources[Name]) || ISFILTERED(IntakeSources[SourceType]),"Place of Residence:"&" "&
			SWITCH(
			    TRUE(),
			    ISFILTERED(IntakeSources[Name]),CONCATENATEX(VALUES(IntakeSources[Abbrev]),IntakeSources[Abbrev],", "),
			    ISFILTERED(IntakeSources[SourceType]),CONCATENATEX(VALUES(IntakeSources[SourceType]),IntakeSources[SourceType],", ")
			))
			
			var diagnosis = 
			IF(NOT(ISFILTERED(DX_Cases[L1]) || ISFILTERED(DX_Cases[L2]) || ISFILTERED(DX_Cases[L3]) || ISFILTERED(DX_Cases[L4])),BLANK(),
			IF(ISFILTERED(DX_Cases[Type]),SELECTEDVALUE(DX_Cases[Type])&" ")&
			"Diagnosis:"&newline&
			SWITCH(
			    TRUE(),
			    ISFILTERED(DX_Cases[L4]),CONCATENATEX(VALUES(DX_Cases[L4]),DX_Cases[L4],", "),
			    ISFILTERED(DX_Cases[L3]),CONCATENATEX(VALUES(DX_Cases[L3]),DX_Cases[L3],", "),
			    ISFILTERED(DX_Cases[L2]),CONCATENATEX(VALUES(DX_Cases[L2]),DX_Cases[L2],", "),
			    ISFILTERED(DX_Cases[L1]),CONCATENATEX(VALUES(DX_Cases[L1]),DX_Cases[L1],", ")
			))
			
			var concatTableShort = FILTER({payer,agerange,placeofresidence},NOT(ISBLANK([Value])))
			var concatTableLong = FILTER({diagnosis},NOT(ISBLANK([Value])))
			
			var stringShort = CONCATENATEX(concatTableShort,[Value],newline)
			var stringLong = CONCATENATEX(concatTableLong,[Value],multiline)
			var stringJoined = FILTER({stringShort,stringLong},NOT(ISBLANK([Value])))
			
			return COALESCE(CONCATENATEX(stringJoined,[Value],multiline),"All")
			```
		lineageTag: 5d05171c-2c72-4b67-83b7-37d583006310

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'ActiveFilters: Test' =
			
			var pcat = IF(ISFILTERED('Payer Buckets'[Payer Categorization]),"Cat")
			var pgroup = IF(ISFILTERED('Payer Buckets'[Payer Grouping]),"Group")
			
			var pvalues = FILTER({pcat,pgroup},ISBLANK([Value])=FALSE())
			var concat = CONCATENATEX(pvalues,[Value],", ")
			return concat
		lineageTag: 139734ac-627f-4634-aa70-3b1387dfdbb3

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '% Minutes Skilled Maintenance' =
			
			DIVIDE(
			    [Total Minutes Skilled Maintenance],
			    [Total Minutes]
			)
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: fa46efaf-5c1d-41e7-8e6a-52dc2fb3b758

	measure 'Minutes per Week (part a)' =
			
			CALCULATE(
			    [Minutes per Week],
			    'Payer Buckets'[Payer Grouping]="(A) Medicare Part A and A-Like"
			)
		formatString: #,0
		displayFolder: Minutes
		lineageTag: 90e95855-c1c8-4228-a2b8-589d9d4e27ce

	partition MeasureTable = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Column1", type text}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{"Column1"})
				in
				    #"Removed Columns"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation
