table ServiceTypes
	lineageTag: 136476f7-a5ba-418b-924b-2cd2b5cfcf49

	measure 'Patients Touched' = ```
			
			// Reads the precomputed ServiceTouch fact (DISTINCTCOUNT) instead of doing set
			// algebra over the fact tables at query time. Period (month/quarter) and Residence
			// arrive as filters on ServiceTouch directly; the ServiceType row arrives via the
			// ServiceTouch -> ServiceTypes relationship for the atomic rows.
			VAR atomic =
			    {
			        "Case", "Track - PT", "Track - OT", "Track - ST",
			        "Nursing Restorative", "Rehab Tech",
			        "Screens", "Wellness", "Electronic Screens"
			    }
			VAR additionalServiceTypes =
			    {
			        "Nursing Restorative", "Rehab Tech",
			        "Screens", "Wellness", "Electronic Screens"
			    }
			VAR currentType = SELECTEDVALUE ( ServiceTypes[ServiceType] )
			VAR censusPats =
			    CALCULATETABLE (
			        VALUES ( ServiceTouch[PatientID] ),
			        REMOVEFILTERS ( ServiceTypes ),
			        ServiceTouch[ServiceType] = "Total Patients"
			    )
			VAR anyPats =
			    CALCULATETABLE (
			        VALUES ( ServiceTouch[PatientID] ),
			        REMOVEFILTERS ( ServiceTypes ),
			        ServiceTouch[ServiceType] IN atomic
			    )
			VAR additionalServicePats =
			    CALCULATETABLE (
			        VALUES ( ServiceTouch[PatientID] ),
			        REMOVEFILTERS ( ServiceTypes ),
			        ServiceTouch[ServiceType] IN additionalServiceTypes
			    )
			VAR total = COUNTROWS ( censusPats )
			RETURN
			    SWITCH (
			        currentType,
			        "Total Patients", total,
			        "Any Service", COUNTROWS ( anyPats ),
			        "Additional Services", COUNTROWS ( additionalServicePats ),
			        "No Service", COUNTROWS ( EXCEPT ( censusPats, anyPats ) ),
			        DISTINCTCOUNT ( ServiceTouch[PatientID] )
			    )
			
			```
		formatString: #,0
		lineageTag: f7cc920d-6ae7-4f76-b35d-93a08e10f63c

	measure 'Patient In Touched List' =
			
			// 1 when the single patient in context contributed to [Patients Touched]
			// for the current ServiceType + period; 0 otherwise. Used to highlight the
			// per-patient timeline. Delegates to the rewritten (fact-based) measure.
			VAR _pid = SELECTEDVALUE ( Patients[PatientID] )
			RETURN
			    IF ( ISBLANK ( _pid ), 0, IF ( [Patients Touched] > 0, 1, 0 ) )
		lineageTag: f98b0e13-9a98-4e83-91b6-d94ebe5f4cdc

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '% Touched (Any Service)' =
			
			VAR num =
			    CALCULATE (
			        DISTINCTCOUNT ( ServiceTouch[PatientID] ),
			        REMOVEFILTERS ( ServiceTypes ),
			        ServiceTouch[ServiceType]
			            IN {
			                "Case", "Track - PT", "Track - OT", "Track - ST",
			                "Nursing Restorative", "Rehab Tech",
			                "Screens", "Wellness", "Electronic Screens"
			            }
			    )
			VAR den =
			    CALCULATE (
			        DISTINCTCOUNT ( ServiceTouch[PatientID] ),
			        REMOVEFILTERS ( ServiceTypes ),
			        ServiceTouch[ServiceType] = "Total Patients"
			    )
			RETURN
			    DIVIDE ( num, den )
		formatString: 0.0%
		lineageTag: c2b71f44-0a3e-4d7a-9f51-1b2c3d4e5f01

	measure '% On Caseload' =
			
			VAR num =
			    CALCULATE (
			        DISTINCTCOUNT ( ServiceTouch[PatientID] ),
			        REMOVEFILTERS ( ServiceTypes ),
			        ServiceTouch[ServiceType] IN { "Case", "Track - PT", "Track - OT", "Track - ST" }
			    )
			VAR den =
			    CALCULATE (
			        DISTINCTCOUNT ( ServiceTouch[PatientID] ),
			        REMOVEFILTERS ( ServiceTypes ),
			        ServiceTouch[ServiceType] = "Total Patients"
			    )
			RETURN
			    DIVIDE ( num, den )
		formatString: 0.0%
		lineageTag: c2b71f44-0a3e-4d7a-9f51-1b2c3d4e5f02

	measure '% On Additional Services' =
			
			VAR num =
			    CALCULATE (
			        DISTINCTCOUNT ( ServiceTouch[PatientID] ),
			        REMOVEFILTERS ( ServiceTypes ),
			        ServiceTouch[ServiceType]
			            IN {
			                "Nursing Restorative", "Rehab Tech",
			                "Screens", "Wellness", "Electronic Screens"
			            }
			    )
			VAR den =
			    CALCULATE (
			        DISTINCTCOUNT ( ServiceTouch[PatientID] ),
			        REMOVEFILTERS ( ServiceTypes ),
			        ServiceTouch[ServiceType] = "Total Patients"
			    )
			RETURN
			    DIVIDE ( num, den )
		formatString: 0.0%
		lineageTag: c2b71f44-0a3e-4d7a-9f51-1b2c3d4e5f03

	measure 'Is Untouched' =
			
			// 1 when the patient in context is in the census for the period but received no
			// service. Drop on a table with Patients[Patient Name] and filter = 1 to list
			// untouched patients for the selected month/quarter.
			VAR inCensus =
			    CALCULATE (
			        DISTINCTCOUNT ( ServiceTouch[PatientID] ),
			        REMOVEFILTERS ( ServiceTypes ),
			        ServiceTouch[ServiceType] = "Total Patients"
			    ) > 0
			VAR inAny =
			    CALCULATE (
			        DISTINCTCOUNT ( ServiceTouch[PatientID] ),
			        REMOVEFILTERS ( ServiceTypes ),
			        ServiceTouch[ServiceType]
			            IN {
			                "Case", "Track - PT", "Track - OT", "Track - ST",
			                "Nursing Restorative", "Rehab Tech",
			                "Screens", "Wellness", "Electronic Screens"
			            }
			    ) > 0
			RETURN
			    IF ( inCensus && NOT inAny, 1, 0 )
		formatString: 0
		lineageTag: c2b71f44-0a3e-4d7a-9f51-1b2c3d4e5f04

	column SortOrder
		formatString: 0
		lineageTag: cda13565-77f8-41ae-a9a1-00df9928828b
		summarizeBy: sum
		isNameInferred
		sourceColumn: [SortOrder]

		annotation SummarizationSetBy = Automatic

	column ServiceType
		lineageTag: 53040886-a01a-4c46-97a8-99fec6f3bc74
		summarizeBy: none
		isNameInferred
		sourceColumn: [ServiceType]
		sortByColumn: SortOrder

		annotation SummarizationSetBy = Automatic

	partition ServiceTypes = calculated
		mode: import
		source = ```
				
				DATATABLE (
				    "SortOrder", INTEGER,
				    "ServiceType", STRING,
				    {
				        { 1, "Case" },
				        { 2, "Track - PT" },
				        { 3, "Track - OT" },
				        { 4, "Track - ST" },
				        { 5, "Additional Services" },
				        { 6, "Nursing Restorative" },
				        { 7, "Rehab Tech" },
				        { 8, "Screens" },
				        { 9, "Electronic Screens" },
				        { 10, "Wellness" },
				        { 11, "Any Service" },
				        { 12, "No Service" },
				        { 13, "Total Patients" },
				        { 14, "% Touched (Any Service)" },
				        { 15, "% On Caseload" },
				        { 16, "% On Additional Services" }
				    }
				)
				
				```

	annotation PBI_Id = 0c8c52d1ff1645419346dad01ef3f12a

