table Service
	lineageTag: d1f0d06f-0626-4513-a232-edddb8c2d9f1

	column ServiceCode
		dataType: string
		isKey
		lineageTag: 744068ec-5e51-485e-aee6-56eff016c506
		summarizeBy: none
		sourceColumn: ServiceCode

		annotation SummarizationSetBy = Automatic

	column Description
		dataType: string
		lineageTag: 73380f66-ca96-4422-8386-6358acb21f01
		summarizeBy: none
		sourceColumn: Description

		annotation SummarizationSetBy = Automatic

	column Abbrev
		dataType: string
		lineageTag: 272a3bcd-3844-4972-90ce-a0580c66b25f
		summarizeBy: none
		sourceColumn: Abbrev

		annotation SummarizationSetBy = Automatic

	column Type
		dataType: string
		lineageTag: b41d22db-d8bb-4642-83b4-9e4e08947b7b
		summarizeBy: none
		sourceColumn: Type

		annotation SummarizationSetBy = Automatic

	column Specialty =
			
			IF(Service[ServiceCode] IN {"97150", "92508"},"Group",
			IF(Service[ServiceCode] IN {"97113"},"Aquatic",
			IF(OR(CONTAINSSTRING(Service[Description],"modal"),Service[ServiceCode] IN {"G0281", "G0283", "G0329"}),"Modality",
			"-None-"
			)))
		lineageTag: 3356a821-96bc-4c8a-9815-b7721eb4616b
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column Category =
			
			IF(Service[Type]="Eval","Evalulation",
			IF(Service[Specialty]<>"-None-",Service[Specialty],
			IF(Service[Abbrev]="","Other",
			IF(LEFT(Service[Abbrev],4)="Well","Wellness",
			Service[Abbrev]
			))))
		lineageTag: a2aa035e-e61a-4fbc-8f37-f64560cf39e5
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition Service = m
		mode: import
		queryGroup: Procedures
		source =
				let
				    Source = Value.NativeQuery(_NetHealthBronze, "SELECT ServiceCode, Description, Abbrev FROM dbo.Service"),
				    #"Added Custom" = Table.AddColumn(Source, "Type", each if Text.Contains(Text.Lower([Description]),"eval") then "Eval" else "Treat"),
				    #"Changed Type" = Table.TransformColumnTypes(#"Added Custom",{{"Type", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

