table Treatments
	lineageTag: 3d89d687-6afb-41b7-879b-898698788a34

	measure 'Max Case Week' =
			
			// CALCULATE(
			//     MAX(Treatments[Case Week]),
			//     ALL(Treatments)
			// )
			
			MAXX(
			    VALUES(Treatments[Case Week]),
			    Treatments[Case Week]
			)
		formatString: #,0
		lineageTag: 527b20e5-63ad-426b-b2e1-85f8c3b47796

	column SessionId
		dataType: int64
		isKey
		formatString: 0
		lineageTag: 4c6a3dd7-8745-4da4-b737-0b77a79b9a23
		summarizeBy: none
		sourceColumn: SessionId

		annotation SummarizationSetBy = Automatic

	column LaborDate
		dataType: dateTime
		formatString: Short Date
		lineageTag: a4ccdca8-1ca1-4775-8aa9-bba416586116
		summarizeBy: none
		sourceColumn: LaborDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column TxTrack_ID
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 201e808f-976c-49f0-aef9-47b2d676b8ea
		summarizeBy: none
		sourceColumn: TxTrack_ID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column CaseIDDate =
			
			// RELATED(StayCases[PatientCase_ID])&" - "&Treatments[LaborDate]
			
			IF(
			    ISBLANK(RELATED(StayCases[PatientCase_ID]))=FALSE(),
			    RELATED(StayCases[PatientCase_ID])&" - "&Treatments[LaborDate]
			)
		lineageTag: f30d2654-ff09-4dd7-93cb-ab03555eb050
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column Person_ID
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 91eb02b2-0d41-4117-8974-bd80030fc68f
		summarizeBy: none
		sourceColumn: Person_ID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column AssistantModifier
		dataType: int64
		formatString: 0
		lineageTag: 42a9c762-55b9-493f-bcb9-8b55ca2634fd
		summarizeBy: sum
		sourceColumn: AssistantModifier

		annotation SummarizationSetBy = Automatic

	column TherapistLabel = RELATED(Employees[Short Name])&IF(Treatments[AssistantModifier]," (A)")
		lineageTag: 5253aad1-f681-4924-b285-b18e55e831f2
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Case Day' =
			
			DATEDIFF(
			    RELATED(StayCases[TherapyStartDate])-1,
			    Treatments[LaborDate],
			    DAY
			)
		formatString: 0
		lineageTag: 85e39d8e-3339-4ddb-a419-87d78f717207
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'Case Week' = ROUNDDOWN((Treatments[Case Day]-1)/7,0)+1
		formatString: 0
		lineageTag: c2ef4dba-59df-47ee-973a-d7b857b4eeae
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	partition Treatments = m
		mode: import
		queryGroup: Visits
		source =
				let
				    Source = dbo_vw_Treatments,
				    #"Removed Other Columns" = Table.SelectColumns(Source,{"Person_ID", "SessionId", "LaborDate", "AssistantModifier", "TxTrack_ID"}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Removed Other Columns",{{"LaborDate", type date}}),
				    #"Removed Duplicates" = Table.Distinct(#"Changed Type", {"SessionId"})
				in
				    #"Removed Duplicates"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

