/// Customer sub-region groupings (Tutera Region 1, Touchstone South, ...).
/// Sourced from the SAME maintained CSV the HAP PDPM Impact report reads, so the
/// two reports cannot drift. Replaces a hand-embedded 117-row Table.FromRows blob
/// that had gone stale (missing Tutera Region 8 / Touchstone East).
/// CCN joins Facility[LicenseNumber], which carries the CMS CCN in Silver.
table CustomerGroups
	lineageTag: d1f6bc88-80bc-40c5-8858-417b94ccb978

	column CCN
		dataType: string
		lineageTag: 32eb2be5-3436-4f62-a48b-6f4f85977946
		summarizeBy: none
		sourceColumn: CCN

		annotation SummarizationSetBy = Automatic

	column 'Customer Group'
		dataType: string
		lineageTag: 75337885-5786-4473-9720-da3085889986
		summarizeBy: none
		sourceColumn: Customer Group

		annotation SummarizationSetBy = Automatic

	partition CustomerGroups = m
		mode: import
		queryGroup: 'Customer Data'
		source =
				let
				    Site = "https://aegis.sharepoint.com/sites/PACSPDPMImpactReports",
				    Root = SharePoint.Contents(Site, [ApiVersion = 15]),
				    LibName = List.First(List.Select(Root[Name], each Text.Lower(_) = "documents" or Text.Lower(_) = "shared documents")),
				    Lib = Root{[Name = LibName]}[Content],
				    Drop = Lib{[Name = "_External Data"]}[Content],
				    File = Drop{[Name = "_customer-groups.csv"]}[Content],
				    Parsed = Table.PromoteHeaders(Csv.Document(File, [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]), [PromoteAllScalars = true]),
				    Clean = Table.SelectRows(Parsed, each [CCN] <> null and Text.Trim([CCN]) <> ""),
				    // CCN is the ONE side of the relationship to Facility[LicenseNumber], so a duplicate
				    // CCN in the CSV must fail the refresh rather than quietly fan out.
				    Unique = Table.Distinct(Clean, {"CCN"}),
				    #"Changed Type" = Table.TransformColumnTypes(Unique,{{"CCN", type text}, {"Customer Group", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation
