table Disciplines
	lineageTag: 518b1b10-a1c3-4a3c-8dd4-24a470ff5de6

	measure Disciplines =
			
			IF(HASONEVALUE(Sentiments[SurveyID]),
			CONCATENATEX(
			    FILTER(Disciplines,Disciplines[Discipline] IN {"PT", "OT", "SLP"}),
			    Disciplines[Discipline],
			    "/"
			))
		lineageTag: fc0032ad-0c6f-4677-9f39-5218861221c8

	column Discipline
		dataType: string
		lineageTag: 4b1e797a-8bf3-4862-a86f-e6329d6d0cbf
		summarizeBy: none
		sourceColumn: Discipline
		sortByColumn: Sort

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column Sort
		dataType: int64
		formatString: 0
		lineageTag: 8c5280be-1878-4891-81fb-907b2562e918
		summarizeBy: none
		sourceColumn: Sort

		annotation SummarizationSetBy = Automatic

	partition Disciplines = m
		mode: import
		queryGroup: 'Survey Support'
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45W8i9LLUrMyVHSUTJUitWJVnJLTM7MySypBAoYgQWCUjMSk4A8YzAvIATINAEz/UFMUzAz2CcAyDZTio0FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Discipline = _t, Sort = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Discipline", type text}, {"Sort", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

