/// Soft security table: which UPNs may see which facilities. The dataflow half is
/// unchanged; the second half (blanket access for the report owners) formerly
/// enumerated Salesforce Aegis_Contract__c and now reads Silver dbo.facility.
table vw_UpnFacilityAccess
	lineageTag: 599bce96-7b5b-464e-88e5-65a0caea05f4

	column FacilityId
		dataType: string
		lineageTag: 8551a37d-f21e-4c27-b89d-3480ee9906fa
		summarizeBy: none
		sourceColumn: FacilityId

		annotation SummarizationSetBy = Automatic

	column UPN
		dataType: string
		lineageTag: 114b526e-13f9-43f8-8e99-fa8a473e16aa
		summarizeBy: none
		sourceColumn: UPN

		annotation SummarizationSetBy = Automatic

	partition vw_UpnFacilityAccess = m
		mode: import
		queryGroup: 'Customer Data'
		source =
				let
				    //UPN table
				    UPN_Source = PowerPlatform.Dataflows(null),
				    UPN_Workspaces = UPN_Source{[Id="Workspaces"]}[Data],
				    UPN_CallWorkspace = UPN_Workspaces{[workspaceId="538303cf-865c-4aae-b405-89ef5e1991aa"]}[Data],
				    UPN_CallDataFlow = UPN_CallWorkspace{[dataflowId="a94779ab-840e-4438-bef8-c6d736e13745"]}[Data],
				    UPN_CallTable = UPN_CallDataFlow{[entity="vw_UpnFacilityAccess",version=""]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(UPN_CallTable,{{"FacilityId", Int64.Type}}),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Changed Type",{{"FacilityId", type text}}),
				    //Aegis facilities (was Salesforce Aegis_Contract__c; now Silver dbo.facility)
				    Facilities_Source = Value.NativeQuery(_SilverSource, "SELECT FacilityNumber FROM dbo.facility WHERE IsTest = 0"),
				    Facilities_Renamed = Table.RenameColumns(Facilities_Source,{{"FacilityNumber", "FacilityId"}}),
				    Facilities_AddedCustom = Table.AddColumn(Facilities_Renamed, "UPN", each "kolby.mangino@healthcraftcreative.com;sara.mcolvin@healthcraftcreative.com;sara.spencer@aegistherapies.com"),
				    Facilities_SplitColumnbyDelimiter = Table.SplitColumn(Facilities_AddedCustom, "UPN", Splitter.SplitTextByDelimiter(";", QuoteStyle.Csv), {"UPN.1", "UPN.2", "UPN.3"}),
				    Facilities_UnpivotedOtherColumns = Table.UnpivotOtherColumns(Facilities_SplitColumnbyDelimiter, {"FacilityId"}, "Attribute", "Value"),
				    Facilities_RemovedColumns = Table.RemoveColumns(Facilities_UnpivotedOtherColumns,{"Attribute"}),
				    Facilities_RenamedColumns2 = Table.RenameColumns(Facilities_RemovedColumns,{{"Value", "UPN"}}),

				    //Combine
				    Combine_Append = Table.Combine({#"Changed Type1", Facilities_RenamedColumns2}),
				    Combine_TrimmedText = Table.TransformColumns(Combine_Append,{{"FacilityId", Text.Trim, type text}}),
				    Combine_LowercasedText = Table.TransformColumns(Combine_TrimmedText,{{"UPN", Text.Lower, type text}}),
				    Combine_RemovedDuplicates = Table.Distinct(Combine_LowercasedText)
				in
				    Combine_RemovedDuplicates

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation
