table CaseTrackDays
	lineageTag: 9eb2e72f-b42c-403d-b292-a83e6ddc3b94

	measure 'Total Unique CaseTrackDays' =
			
			DISTINCTCOUNT(CaseTrackDays[TrackDate])
		formatString: #,0
		lineageTag: 9a7cdb3e-ed38-4abe-8427-ac9fd277b5f5

	column TxTrack_ID
		dataType: int64
		formatString: 0
		lineageTag: df7998c6-1390-4b9c-a07d-a44e9712cd99
		summarizeBy: none
		sourceColumn: TxTrack_ID

		annotation SummarizationSetBy = Automatic

	column TrackDate
		dataType: dateTime
		formatString: Short Date
		lineageTag: e2ce5a37-075f-449f-b847-b051d6c514f0
		summarizeBy: none
		sourceColumn: TrackDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	partition CaseTrackDays = m
		mode: import
		queryGroup: Patient
		source =
				// Daily TrackDate grain for ALOS / Minutes-per-Week. Expanded LOCALLY
				// from the in-memory CaseTracks set (~237K rows) via List.Dates — NOT
				// in SQL. A server-side tally expansion was tried and reverted: it is
				// far slower here because the range join cross-products (~36s just to
				// count) and ships all ~8.7M day-rows over the wire, vs transferring
				// 237K track rows and exploding them cheaply in the mashup engine.
				// GUARD RAIL: daysCount capped at 3651 (10 years) so a junk track
				// (max observed span ~21yr; only 21 tracks of 2.55M exceed 10yr, all
				// data errors) can't balloon the explosion. Open tracks (null EndDate)
				// run to today, matching the prior behavior.
				let
				    Source = CaseTracks,
				    #"Removed Other Columns" = Table.SelectColumns(CaseTracks,{"TxTrack_ID", "StartDate", "EndDate"}),
				    #"Added Custom" = Table.AddColumn(
				    #"Removed Other Columns",
				    "ListOfDates",
				    each
				        let
				            actualEndDate = if [EndDate] = null then Date.From(DateTime.LocalNow()) else [EndDate],
				            daysCount = List.Min({Duration.Days(actualEndDate - [StartDate]) + 1, 3651})
				        in
				            List.Dates([StartDate], daysCount, #duration(1, 0, 0, 0))
				),
				    #"Expanded ListOfDates" = Table.ExpandListColumn(#"Added Custom", "ListOfDates"),
				    #"Removed Columns" = Table.RemoveColumns(#"Expanded ListOfDates",{"StartDate", "EndDate"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Removed Columns",{{"ListOfDates", "TrackDate"}}),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Renamed Columns",{{"TrackDate", type date}})
				in
				    #"Changed Type1"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

