table Chain
	lineageTag: 657c25e3-3c08-4758-9be1-358671d9b79d

	column Id
		dataType: string
		isHidden
		isKey
		lineageTag: ae9d9ded-c81a-4538-98fa-71b616b4b95e
		summarizeBy: none
		sourceColumn: Id

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Name
		dataType: string
		lineageTag: bf422674-5689-4a8d-beaa-acc1fe74ad58
		summarizeBy: none
		sourceColumn: Name

		annotation SummarizationSetBy = Automatic

	partition Chain = m
		mode: import
		queryGroup: Places
		source =
				let
				    Source = Value.NativeQuery(_SilverSource, "SELECT DISTINCT ChainName FROM dbo.facility WHERE IsTest = 0 AND ChainName IS NOT NULL AND LTRIM(RTRIM(ChainName)) <> ''"),
				    #"Added Id" = Table.AddColumn(Source, "Id", each [ChainName], type text),
				    #"Renamed Columns" = Table.RenameColumns(#"Added Id",{{"ChainName", "Name"}})
				in
				    #"Renamed Columns"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

