table DestinationPage
	lineageTag: a56a74c4-81fc-4844-82a0-59a90c406234

	measure 'Drill Destination' = SELECTEDVALUE(DestinationPage[Destination])
		lineageTag: e927511a-0306-4a22-b78b-5d4d94837695

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Destination
		dataType: string
		lineageTag: f166f671-5323-47bd-aacb-bbc4f2d07253
		summarizeBy: none
		sourceColumn: Destination
		sortByColumn: 'Sort Order'

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column 'Intended Audience'
		dataType: string
		lineageTag: 26a64a7d-6e27-41c5-83c3-469bd7b5e730
		summarizeBy: none
		sourceColumn: Intended Audience

		annotation SummarizationSetBy = Automatic

	column 'Sort Order'
		dataType: int64
		formatString: 0
		lineageTag: 84516e81-9e05-4c29-a027-11a49fa97bef
		summarizeBy: sum
		sourceColumn: Sort Order

		annotation SummarizationSetBy = Automatic

	column Label
		dataType: string
		lineageTag: 3e64d0ef-20fa-4f7f-bdc8-a59f1e7b064c
		summarizeBy: none
		sourceColumn: Label
		sortByColumn: 'Sort Order'

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	partition DestinationPage = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("bY47DsIwDECvYmUqUhmAI0QMbEDHqINV3GIpnypNi3J7zKcCKjZb7/nJxqgjJiafYN/zEC4E1egcxqzKmZTQomObocFIHU8UhW0+fHkJRf8C6xYb9t1K1aVROlxDTKCD6zGK7yWgxyEF9+xtH+tSgaJ5Gz+pg08UPVrQ8hCcRrScMpxpYrpJZsYy7r7WfzYUPNPgbZZ8fQc=", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Destination = _t, #"Intended Audience" = _t, #"Sort Order" = _t, Label = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Destination", type text}, {"Intended Audience", type text}, {"Sort Order", Int64.Type}, {"Label", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

