/// vw_AllEvalsAndDischargesLight
table Documents
	lineageTag: 3b37687d-db9b-4a4e-80bf-0305d92d9590

	measure 'Total Documents' = COUNTROWS(Documents)
		formatString: #,0
		lineageTag: 20147533-0130-4260-a109-48f2e1f68c74

	column TxDocument_ID
		dataType: int64
		isHidden
		isKey
		formatString: 0
		lineageTag: fb811cdb-c29a-428b-a0fc-0bd9da996554
		summarizeBy: none
		sourceColumn: TxDocument_ID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column TxTrack_ID
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 0d806454-be9f-47b1-829d-2314fba16cef
		summarizeBy: none
		sourceColumn: TxTrack_ID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column DocumentType
		dataType: string
		lineageTag: 0a14af2d-8c96-48a5-8500-9a2347183bf7
		summarizeBy: none
		sourceColumn: DocumentType

		annotation SummarizationSetBy = Automatic

	column Physician_ID
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 1e34ec97-1689-43b9-9766-0828227b2358
		summarizeBy: none
		sourceColumn: Physician_ID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition Documents = m
		mode: directQuery
		queryGroup: Outcomes
		source =
				let
				    Source = #"dbo vw_AllEvalsAndDischargesLight",
				    #"Replaced Value" = Table.ReplaceValue(Source,"EVAL","ADMIT",Replacer.ReplaceText,{"DocumentType"})
				in
				    #"Replaced Value"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

