table EDD
	lineageTag: fc71e8f6-f976-499d-b03d-c02d556582ad

	column ID
		dataType: int64
		formatString: 0
		lineageTag: c1e3ab47-a5f4-402e-a898-8f00e6656581
		summarizeBy: none
		sourceColumn: ID

		annotation SummarizationSetBy = Automatic

	column DisplayValue
		dataType: string
		lineageTag: 7570b2f1-3bd3-45ce-a00b-0c5ce072349f
		summarizeBy: none
		sourceColumn: DisplayValue

		annotation SummarizationSetBy = Automatic

	column Label
		dataType: string
		lineageTag: f4f77f0d-7782-476d-8718-d1af2bcae5ab
		summarizeBy: none
		sourceColumn: Label

		annotation SummarizationSetBy = Automatic

	partition EDD = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45WMjK0MDNW0lFy9HEDks75ubmleZkllUqxOhA5E6Coe1F+aYGCR35uKjYlppZAUZCkgoanJlYzDGAKtLFKGwFFPXFYbw4U9S/JSC2C0zAZM5iIgk+IM5ANImFyhjC54phSAwMjc5xuNzMFioZkZBYjGxILAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [ID = _t, DisplayValue = _t, Label = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"ID", Int64.Type}, {"DisplayValue", type text}, {"Label", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

