table EmployeeBasicInfo
	lineageTag: b7fd8bfc-d16e-4092-965a-0605a861dac3

	column EmployeeNo
		dataType: string
		lineageTag: daef7094-0ddb-4e8b-9af4-474f316478a0
		summarizeBy: none
		sourceColumn: EmployeeNo

		annotation SummarizationSetBy = Automatic

	column Person_ID
		dataType: int64
		formatString: 0
		lineageTag: 5cf38f65-4f0a-453b-91d2-a1579b1a669f
		summarizeBy: none
		sourceColumn: Person_ID

		annotation SummarizationSetBy = Automatic

	column 'Therapist Name'
		dataType: string
		lineageTag: 43f58bc9-c689-4401-9fcc-ea0b8fc12733
		summarizeBy: none
		sourceColumn: Therapist Name

		annotation SummarizationSetBy = Automatic

	column JobTitle
		dataType: string
		lineageTag: bc432d8f-a035-4ad4-8b27-eae5bb90f6c1
		summarizeBy: none
		sourceColumn: JobTitle

		annotation SummarizationSetBy = Automatic

	column Credentials
		dataType: string
		lineageTag: 64b9b580-0aaf-4d1c-b027-71fcfa0f429a
		summarizeBy: none
		sourceColumn: Credentials

		annotation SummarizationSetBy = Automatic

	column 'Therapist Label' = EmployeeBasicInfo[Therapist Name]&" ("&EmployeeBasicInfo[JobTitle]&")"
		lineageTag: c35bfe96-babf-4431-968d-6408045e260e
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column JobCodeId
		dataType: int64
		formatString: 0
		lineageTag: 8898ece1-44ac-46d2-97ae-2669230d3403
		summarizeBy: none
		sourceColumn: JobCodeId

		annotation SummarizationSetBy = Automatic

	partition EmployeeBasicInfo = m
		mode: import
		queryGroup: People
		source =
				let
				    Source = Value.NativeQuery(_SilverSource, "SELECT NetHealthId AS Person_ID, EmployeeNumber AS EmployeeNo, FullName, JobTitle, Discipline AS Credentials, TRY_CAST(JobCode AS int) AS JobCodeId FROM (SELECT *, ROW_NUMBER() OVER (PARTITION BY NetHealthId ORDER BY SourceType, Username) AS rn FROM dbo.employee WHERE NetHealthId IS NOT NULL AND ISNULL(EmployeeNumber,'') <> '' AND EmployeeNumber <> '99999') x WHERE x.rn = 1"),
				    #"Renamed Columns" = Table.RenameColumns(Source,{{"FullName", "Therapist Name"}})
				in
				    #"Renamed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

