table FTEType
	lineageTag: c1b71a28-46ec-4eb2-b9db-59402de0a4b5

	column 'Employee ID'
		dataType: string
		lineageTag: c3feed6b-87fd-4934-93f5-61fbb1096e5d
		summarizeBy: none
		sourceColumn: Employee ID

		annotation SummarizationSetBy = Automatic

	column FTE
		dataType: double
		lineageTag: ec04b21d-848e-4195-8f98-e1611f6b5ebf
		summarizeBy: sum
		sourceColumn: FTE

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Employee Type'
		dataType: string
		lineageTag: 805723ef-a389-4411-b996-bd685378abd0
		summarizeBy: none
		sourceColumn: Employee Type

		annotation SummarizationSetBy = Automatic

	column Type =
			
			// SWITCH(
			//     FTEType[Employee Type],
			//     "Casual","PRN",
			//     "Casual ACA","PRN",
			//     "Full or Part Time"
			// )
			
			SWITCH(
			    TRUE(),
			    CONTAINSSTRING(FTEType[Employee Type],"Casual"),"Casual",
			    CONTAINSSTRING(FTEType[Employee Type],"Part Time"),"Part Time",
			    "Full Time"
			)
		lineageTag: ed6e59d8-ddea-42e7-8c65-0e7bf942b68e
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition FTEType = m
		mode: directQuery
		queryGroup: People
		source =
				let
				    Source = excel_Employee_FTE_status_vs_patient_outcomes_WD_Roster,
				    #"Removed Other Columns" = Table.SelectColumns(Source,{"Employee ID", "FTE", "Employee Type"}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Removed Other Columns",{{"Employee ID", type text}, {"FTE", type number}, {"Employee Type", type text}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

