table 'Outcomes Breakdown'
	lineageTag: 09025d1a-320b-4e40-83bf-eac7f4dd098c

	measure 'Case Count' =
			
			IF(HASONEVALUE('Outcomes Breakdown'[Group]),
			    SWITCH(
			        SELECTEDVALUE('Outcomes Breakdown'[Group]),
			        "Improved",CALCULATE([Total Cases],FILTER(StayCases,[Gain]>0)),
			        "No Change",CALCULATE([Total Cases],FILTER(StayCases,[Gain]=0 && ISBLANK([Admit Level])=FALSE())),
			        "Declined",CALCULATE([Total Cases],FILTER(StayCases,[Gain]<0)),
			        "N/A",CALCULATE([Total Cases],FILTER(StayCases,ISBLANK([Gain])))
			    ),
			    [Total Cases]
			)
		formatString: #,0
		lineageTag: 68e44d37-22c9-49b2-b0b3-cd6fca659609

	column Group
		lineageTag: 1a599f0b-0746-45c0-b9af-944203daf990
		summarizeBy: none
		isNameInferred
		sourceColumn: [Group]
		sortByColumn: Order

		annotation SummarizationSetBy = Automatic

	column Order
		formatString: 0
		lineageTag: d20ab8ea-f4c4-4831-b260-97f16863eb71
		summarizeBy: sum
		isNameInferred
		sourceColumn: [Order]

		annotation SummarizationSetBy = Automatic

	partition 'Outcomes Breakdown' = calculated
		mode: directQuery
		source =
				
				UNION(
				    ROW("Group","Improved","Order",1),
				    ROW("Group","No Change","Order",2),
				    ROW("Group","Declined","Order",3),
				    ROW("Group","N/A","Order",4)
				)

	annotation PBI_Id = c3a96b04c9ba40b3bf46d004c95b43a0

