table ServiceTypes
	lineageTag: 136476f7-a5ba-418b-924b-2cd2b5cfcf49

	measure 'Patients Touched' = ```

			VAR currentType = SELECTEDVALUE ( ServiceTypes[ServiceType] )
			VAR monthStart  = MIN ( 'Calendar'[Date] )
			VAR monthEnd    = EOMONTH ( monthStart, 0 )

			// Patients with an active stay in this month (the census denominator)
			VAR totalPatients =
			    CALCULATETABLE (
			        VALUES ( PatientStays[PatientID] ),
			        REMOVEFILTERS ( 'Calendar' ),
			        PatientStays[AdmitDate] <= monthEnd,
			        PatientStays[DischargeDate] >= monthStart
			            || ISBLANK ( PatientStays[DischargeDate] )
			    )

			// Cases: patient had an active case overlapping the month
			VAR casePats =
			    CALCULATETABLE (
			        VALUES ( PatientStays[PatientID] ),
			        REMOVEFILTERS ( 'Calendar' ),
			        StayCases[TherapyStartDate] <= monthEnd,
			        StayCases[TherapyEndDate] >= monthStart
			            || ISBLANK ( StayCases[TherapyEndDate] )
			    )

			// Tracks by discipline
			VAR trackPT =
			    CALCULATETABLE (
			        VALUES ( PatientStays[PatientID] ),
			        REMOVEFILTERS ( 'Calendar' ),
			        CaseTracks[StartDate] <= monthEnd,
			        ( CaseTracks[EndDate] >= monthStart || ISBLANK ( CaseTracks[EndDate] ) ),
			        Disciplines[Discipline] = "PT"
			    )

			VAR trackOT =
			    CALCULATETABLE (
			        VALUES ( PatientStays[PatientID] ),
			        REMOVEFILTERS ( 'Calendar' ),
			        CaseTracks[StartDate] <= monthEnd,
			        ( CaseTracks[EndDate] >= monthStart || ISBLANK ( CaseTracks[EndDate] ) ),
			        Disciplines[Discipline] = "OT"
			    )

			VAR trackST =
			    CALCULATETABLE (
			        VALUES ( PatientStays[PatientID] ),
			        REMOVEFILTERS ( 'Calendar' ),
			        CaseTracks[StartDate] <= monthEnd,
			        ( CaseTracks[EndDate] >= monthStart || ISBLANK ( CaseTracks[EndDate] ) ),
			        Disciplines[Discipline] = "ST"
			    )

			// PLOS by category (point events: CreatedDate falls within the month)
			VAR plosNR =
			    CALCULATETABLE (
			        VALUES ( Patients[PatientID] ),
			        REMOVEFILTERS ( 'Calendar' ),
			        PatientLevelOptionalServices_Instance[CreatedDate] >= monthStart,
			        PatientLevelOptionalServices_Instance[CreatedDate] <= monthEnd,
			        PatientLevelOptionalServices_Service[Category] = "Nursing Restorative"
			    )

			VAR plosRT =
			    CALCULATETABLE (
			        VALUES ( Patients[PatientID] ),
			        REMOVEFILTERS ( 'Calendar' ),
			        PatientLevelOptionalServices_Instance[CreatedDate] >= monthStart,
			        PatientLevelOptionalServices_Instance[CreatedDate] <= monthEnd,
			        PatientLevelOptionalServices_Service[Category] = "Rehab Tech"
			    )

			// Screens: PatientScreens (DateCompleted) + PLOS (CreatedDate)
			VAR plosSC =
			    DISTINCT (
			        UNION (
			            CALCULATETABLE (
			                VALUES ( PatientScreens[Resolved PatientID] ),
			                REMOVEFILTERS ( 'Calendar' ),
			                PatientScreens[DateCompleted] >= monthStart,
			                PatientScreens[DateCompleted] <= monthEnd
			            ),
			            CALCULATETABLE (
			                VALUES ( Patients[PatientID] ),
			                REMOVEFILTERS ( 'Calendar' ),
			                PatientLevelOptionalServices_Instance[CreatedDate] >= monthStart,
			                PatientLevelOptionalServices_Instance[CreatedDate] <= monthEnd,
			                PatientLevelOptionalServices_Service[Category] = "Screens"
			            )
			        )
			    )

			VAR plosWL =
			    CALCULATETABLE (
			        VALUES ( Patients[PatientID] ),
			        REMOVEFILTERS ( 'Calendar' ),
			        PatientLevelOptionalServices_Instance[CreatedDate] >= monthStart,
			        PatientLevelOptionalServices_Instance[CreatedDate] <= monthEnd,
			        PatientLevelOptionalServices_Service[Category] = "Wellness"
			    )

			// PLOS - Any: distinct patients touched by any PLOS category
			VAR plosAny =
			    DISTINCT ( UNION ( plosNR, plosRT, plosSC, plosWL ) )

			// Union of all patients touched by any service (de-duplicated)
			VAR anyServicePats =
			    DISTINCT (
			        UNION ( casePats, trackPT, trackOT, trackST, plosNR, plosRT, plosSC, plosWL )
			    )

			// Patients in the census NOT touched by any service
			VAR noServicePats =
			    EXCEPT ( totalPatients, anyServicePats )

			RETURN
			SWITCH (
			    currentType,
			    "Case",                         COUNTROWS ( casePats ),
			    "Track - PT",                   COUNTROWS ( trackPT ),
			    "Track - OT",                   COUNTROWS ( trackOT ),
			    "Track - ST",                   COUNTROWS ( trackST ),
			    "PLOS - Any",                   COUNTROWS ( plosAny ),
			    "PLOS - Nursing Restorative",   COUNTROWS ( plosNR ),
			    "PLOS - Rehab Tech",            COUNTROWS ( plosRT ),
			    "PLOS - Screens",               COUNTROWS ( plosSC ),
			    "PLOS - Wellness",              COUNTROWS ( plosWL ),
			    "Any Service",                  COUNTROWS ( anyServicePats ),
			    "No Service",                   COUNTROWS ( noServicePats ),
			    "Total Patients",               COUNTROWS ( totalPatients ),
			    BLANK ()
			)

			```
		formatString: #,0
		lineageTag: f7cc920d-6ae7-4f76-b35d-93a08e10f63c

	measure 'Patient In Touched List' =

			VAR _pid = SELECTEDVALUE ( Patients[PatientID] )
			VAR currentType = SELECTEDVALUE ( ServiceTypes[ServiceType] )
			VAR monthStart = MIN ( 'Calendar'[Date] )
			VAR monthEnd = EOMONTH ( monthStart, 0 )

			// Return 0 if no patient, month, or type in context
			RETURN
			    IF (
			        ISBLANK ( _pid ) || ISBLANK ( currentType ) || ISBLANK ( monthStart ),
			        0,
			        VAR totalPatients =
			            CALCULATETABLE (
			                VALUES ( PatientStays[PatientID] ),
			                REMOVEFILTERS ( 'Calendar' ),
			                PatientStays[AdmitDate] <= monthEnd,
			                PatientStays[DischargeDate] >= monthStart
			                    || ISBLANK ( PatientStays[DischargeDate] )
			            )
			        VAR casePats =
			            CALCULATETABLE (
			                VALUES ( PatientStays[PatientID] ),
			                REMOVEFILTERS ( 'Calendar' ),
			                StayCases[TherapyStartDate] <= monthEnd,
			                StayCases[TherapyEndDate] >= monthStart
			                    || ISBLANK ( StayCases[TherapyEndDate] )
			            )
			        VAR trackPT =
			            CALCULATETABLE (
			                VALUES ( PatientStays[PatientID] ),
			                REMOVEFILTERS ( 'Calendar' ),
			                CaseTracks[StartDate] <= monthEnd,
			                ( CaseTracks[EndDate] >= monthStart || ISBLANK ( CaseTracks[EndDate] ) ),
			                Disciplines[Discipline] = "PT"
			            )
			        VAR trackOT =
			            CALCULATETABLE (
			                VALUES ( PatientStays[PatientID] ),
			                REMOVEFILTERS ( 'Calendar' ),
			                CaseTracks[StartDate] <= monthEnd,
			                ( CaseTracks[EndDate] >= monthStart || ISBLANK ( CaseTracks[EndDate] ) ),
			                Disciplines[Discipline] = "OT"
			            )
			        VAR trackST =
			            CALCULATETABLE (
			                VALUES ( PatientStays[PatientID] ),
			                REMOVEFILTERS ( 'Calendar' ),
			                CaseTracks[StartDate] <= monthEnd,
			                ( CaseTracks[EndDate] >= monthStart || ISBLANK ( CaseTracks[EndDate] ) ),
			                Disciplines[Discipline] = "ST"
			            )
			        VAR plosNR =
			            CALCULATETABLE (
			                VALUES ( Patients[PatientID] ),
			                REMOVEFILTERS ( 'Calendar' ),
			                PatientLevelOptionalServices_Instance[CreatedDate] >= monthStart,
			                PatientLevelOptionalServices_Instance[CreatedDate] <= monthEnd,
			                PatientLevelOptionalServices_Service[Category] = "Nursing Restorative"
			            )
			        VAR plosRT =
			            CALCULATETABLE (
			                VALUES ( Patients[PatientID] ),
			                REMOVEFILTERS ( 'Calendar' ),
			                PatientLevelOptionalServices_Instance[CreatedDate] >= monthStart,
			                PatientLevelOptionalServices_Instance[CreatedDate] <= monthEnd,
			                PatientLevelOptionalServices_Service[Category] = "Rehab Tech"
			            )
			        VAR plosSC =
			            DISTINCT (
			                UNION (
			                    CALCULATETABLE (
			                        VALUES ( PatientScreens[Resolved PatientID] ),
			                        REMOVEFILTERS ( 'Calendar' ),
			                        PatientScreens[DateCompleted] >= monthStart,
			                        PatientScreens[DateCompleted] <= monthEnd
			                    ),
			                    CALCULATETABLE (
			                        VALUES ( Patients[PatientID] ),
			                        REMOVEFILTERS ( 'Calendar' ),
			                        PatientLevelOptionalServices_Instance[CreatedDate] >= monthStart,
			                        PatientLevelOptionalServices_Instance[CreatedDate] <= monthEnd,
			                        PatientLevelOptionalServices_Service[Category] = "Screens"
			                    )
			                )
			            )
			        VAR plosWL =
			            CALCULATETABLE (
			                VALUES ( Patients[PatientID] ),
			                REMOVEFILTERS ( 'Calendar' ),
			                PatientLevelOptionalServices_Instance[CreatedDate] >= monthStart,
			                PatientLevelOptionalServices_Instance[CreatedDate] <= monthEnd,
			                PatientLevelOptionalServices_Service[Category] = "Wellness"
			            )
			        VAR plosAny = DISTINCT ( UNION ( plosNR, plosRT, plosSC, plosWL ) )
			        VAR anyServicePats =
			            DISTINCT (
			                UNION ( casePats, trackPT, trackOT, trackST, plosNR, plosRT, plosSC, plosWL )
			            )
			        VAR noServicePats = EXCEPT ( totalPatients, anyServicePats )

			        // Normalize sets to single "PatientID" column for membership check
			        VAR chk = SELECTCOLUMNS ( ROW ( "PatientID", _pid ), "PatientID", [PatientID] )
			        VAR inCase = COUNTROWS ( INTERSECT ( SELECTCOLUMNS ( casePats, "PatientID", PatientStays[PatientID] ), chk ) ) > 0
			        VAR inTrackPT = COUNTROWS ( INTERSECT ( SELECTCOLUMNS ( trackPT, "PatientID", PatientStays[PatientID] ), chk ) ) > 0
			        VAR inTrackOT = COUNTROWS ( INTERSECT ( SELECTCOLUMNS ( trackOT, "PatientID", PatientStays[PatientID] ), chk ) ) > 0
			        VAR inTrackST = COUNTROWS ( INTERSECT ( SELECTCOLUMNS ( trackST, "PatientID", PatientStays[PatientID] ), chk ) ) > 0
			        VAR inPlosNR = COUNTROWS ( INTERSECT ( SELECTCOLUMNS ( plosNR, "PatientID", Patients[PatientID] ), chk ) ) > 0
			        VAR inPlosRT = COUNTROWS ( INTERSECT ( SELECTCOLUMNS ( plosRT, "PatientID", Patients[PatientID] ), chk ) ) > 0
			        VAR inPlosWL = COUNTROWS ( INTERSECT ( SELECTCOLUMNS ( plosWL, "PatientID", Patients[PatientID] ), chk ) ) > 0
			        VAR plosSC1 =
			            SELECTCOLUMNS (
			                CALCULATETABLE (
			                    VALUES ( PatientScreens[Resolved PatientID] ),
			                    REMOVEFILTERS ( 'Calendar' ),
			                    PatientScreens[DateCompleted] >= monthStart,
			                    PatientScreens[DateCompleted] <= monthEnd
			                ),
			                "PatientID", PatientScreens[Resolved PatientID]
			            )
			        VAR plosSC2 =
			            SELECTCOLUMNS (
			                CALCULATETABLE (
			                    VALUES ( Patients[PatientID] ),
			                    REMOVEFILTERS ( 'Calendar' ),
			                    PatientLevelOptionalServices_Instance[CreatedDate] >= monthStart,
			                    PatientLevelOptionalServices_Instance[CreatedDate] <= monthEnd,
			                    PatientLevelOptionalServices_Service[Category] = "Screens"
			                ),
			                "PatientID", Patients[PatientID]
			            )
			        VAR inPlosSC =
			            COUNTROWS ( INTERSECT ( plosSC1, chk ) ) > 0
			                || COUNTROWS ( INTERSECT ( plosSC2, chk ) ) > 0
			        VAR inPlosAny = inPlosNR || inPlosRT || inPlosSC || inPlosWL
			        VAR inAnyService = inCase || inTrackPT || inTrackOT || inTrackST || inPlosNR || inPlosRT || inPlosSC || inPlosWL
			        VAR inTotal = COUNTROWS ( INTERSECT ( SELECTCOLUMNS ( totalPatients, "PatientID", PatientStays[PatientID] ), chk ) ) > 0
			        VAR inNoService = COUNTROWS ( INTERSECT ( SELECTCOLUMNS ( noServicePats, "PatientID", PatientStays[PatientID] ), chk ) ) > 0

			        RETURN
			            SWITCH (
			                currentType,
			                "Case", inCase,
			                "Track - PT", inTrackPT,
			                "Track - OT", inTrackOT,
			                "Track - ST", inTrackST,
			                "PLOS - Any", inPlosAny,
			                "PLOS - Nursing Restorative", inPlosNR,
			                "PLOS - Rehab Tech", inPlosRT,
			                "PLOS - Screens", inPlosSC,
			                "PLOS - Wellness", inPlosWL,
			                "Any Service", inAnyService,
			                "No Service", inNoService,
			                "Total Patients", inTotal,
			                0
			            )
			    + 0
			)
		lineageTag: f98b0e13-9a98-4e83-91b6-d94ebe5f4cdc

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column SortOrder
		formatString: 0
		lineageTag: cda13565-77f8-41ae-a9a1-00df9928828b
		summarizeBy: sum
		isNameInferred
		sourceColumn: [SortOrder]

		annotation SummarizationSetBy = Automatic

	column ServiceType
		lineageTag: 53040886-a01a-4c46-97a8-99fec6f3bc74
		summarizeBy: none
		isNameInferred
		sourceColumn: [ServiceType]
		sortByColumn: SortOrder

		annotation SummarizationSetBy = Automatic

	partition ServiceTypes = calculated
		mode: import
		source = ```

				DATATABLE (
				    "SortOrder", INTEGER,
				    "ServiceType", STRING,
				    {
				        { 1, "Case" },
				        { 2, "Track - PT" },
				        { 3, "Track - OT" },
				        { 4, "Track - ST" },
				        { 5, "PLOS - Any" },
				        { 6, "PLOS - Nursing Restorative" },
				        { 7, "PLOS - Rehab Tech" },
				        { 8, "PLOS - Screens" },
				        { 9, "PLOS - Wellness" },
				        { 10, "Any Service" },
				        { 11, "No Service" },
				        { 12, "Total Patients" },
				        { 13, "% Touched (Any Service)" },
				        { 14, "% On Caseload" },
				        { 15, "% On PLOS" }
				    }
				)

				```

	annotation PBI_Id = 0c8c52d1ff1645419346dad01ef3f12a
