table 'Service Rows'
	lineageTag: a32ca62e-6a0a-470d-af5b-e0b5f4cc7dd6

	measure 'Rows Title' = "Results by Utilization of "&SELECTEDVALUE('Service Rows'[Service Rows Name])
		lineageTag: 1a3873b4-c36b-450b-8dd7-c1e001c2bfab

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Service Rows'
		lineageTag: f3c726d1-d479-4a7c-8032-43ba3fb38f95
		summarizeBy: none
		sourceColumn: [Value1]
		sortByColumn: 'Service Rows Order'

		relatedColumnDetails
			groupByColumn: 'Service Rows Fields'

		annotation SummarizationSetBy = Automatic

	column 'Service Rows Fields'
		isHidden
		lineageTag: 12e2cf63-6259-4967-92a2-e4b0d4d1959c
		summarizeBy: none
		sourceColumn: [Value2]
		sortByColumn: 'Service Rows Order'

		extendedProperty ParameterMetadata =
				{
				  "version": 3,
				  "kind": 2
				}

		annotation SummarizationSetBy = Automatic

	column 'Service Rows Order'
		isHidden
		formatString: 0
		lineageTag: 10b74959-b84e-47ae-8c36-9275c3031d2a
		summarizeBy: sum
		sourceColumn: [Value3]

		annotation SummarizationSetBy = Automatic

	column 'Service Rows Name' = 'Service Rows'[Service Rows]
		lineageTag: e4a6ca2b-a520-41a7-aced-eeecb69fe745
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition 'Service Rows' = calculated
		mode: import
		source =
				{
				    ("Aquatic Therapy", NAMEOF('StayCases'[Uses: Aquatic Therapy]), 0),
				    ("Group Therapy", NAMEOF('StayCases'[Uses: Group Therapy]), 1),
				    ("Modalities", NAMEOF('StayCases'[Uses: Modalities]), 2),
				    ("Skilled Maintenance", NAMEOF('StayCases'[Uses: Skilled Maintenance]), 3),
				    ("Telehealth", NAMEOF('StayCases'[Uses: Telehealth]), 4)
				}

	annotation PBI_Id = cdf3bcf0e3d44a94808597f0a6416dc7

