table VW_NHAegisFacilities
	lineageTag: 7dd4cb6d-457e-4cdf-97ca-ee634e0711f8

	column FacilityId
		dataType: string
		lineageTag: 61cf0a7d-f68b-46a4-a7b9-090fce6867c9
		summarizeBy: none
		sourceColumn: FacilityId

		annotation SummarizationSetBy = Automatic

	column District
		dataType: string
		lineageTag: 7b31e9a4-f993-4dea-8054-ab6e299c68cb
		summarizeBy: none
		sourceColumn: District

		annotation SummarizationSetBy = Automatic

	column Region
		dataType: string
		lineageTag: 15e698b4-37e0-4eaa-a0a0-5dbe5af79892
		summarizeBy: none
		sourceColumn: Region

		annotation SummarizationSetBy = Automatic

	column Division
		dataType: string
		lineageTag: ef4be545-c21a-4b7a-90d3-f94a9a335fe5
		summarizeBy: none
		sourceColumn: Division

		annotation SummarizationSetBy = Automatic

	column IsValid = VW_NHAegisFacilities[Division] IN {"5500 (Direct Bill)", "8450 (Contract Rehab)"}
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 72b2ee4f-7d8b-45d5-86bb-fb1d974e9cd3
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column Department =
			
			SWITCH(
			    VW_NHAegisFacilities[Division],
			    "5500 (Direct Bill)","Senior Living",
			    "All Other"
			)
		lineageTag: 374a723a-5f52-466c-9e74-c49bb769eb3d
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition VW_NHAegisFacilities = m
		mode: import
		queryGroup: Management
		source =
				let
				    Source = Value.NativeQuery(_SilverSource, "SELECT RIGHT('00000' + LTRIM(RTRIM(CAST(FacilityNumber AS varchar(10)))), 5) AS FacilityId, CAST(DistrictNumber AS varchar(20)) AS District, CAST(AreaNumber AS varchar(20)) AS Region, CAST(TRY_CAST(RegionNumber AS int) AS varchar(10)) AS Division FROM dbo.facilityhierarchy"),
				    #"Replaced Value" = Table.ReplaceValue(Source,"5555","5555 (Closed Locations)",Replacer.ReplaceText,{"Division"}),
				    #"Replaced Value1" = Table.ReplaceValue(#"Replaced Value","5500","5500 (Direct Bill)",Replacer.ReplaceText,{"Division"}),
				    #"Replaced Value2" = Table.ReplaceValue(#"Replaced Value1","6500","6500 (PACS Consulting)",Replacer.ReplaceText,{"Division"}),
				    #"Replaced Value3" = Table.ReplaceValue(#"Replaced Value2","8450","8450 (Contract Rehab)",Replacer.ReplaceText,{"Division"})
				in
				    #"Replaced Value3"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

