table vw_PatientPayers
	lineageTag: 876298ed-e8c0-4dc4-9ac4-7d39121b9894

	measure 'Total Payer Segments' = COUNTROWS(vw_PatientPayers)
		formatString: #,0
		lineageTag: 6b56cc88-b9c5-4c12-92a1-a604911d462e

	measure 'Total Payer Group Segments' = DISTINCTCOUNT(vw_PatientPayers[Payer Group])
		formatString: 0
		lineageTag: 1f8022aa-c208-48a9-9a0a-6e5faf36a991

	measure 'Min Payer Start' = MIN(vw_PatientPayers[FromDate])
		lineageTag: 162f3a94-5293-4a88-be99-9c87cddf5729

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column CaseID
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: b0391f5a-e018-4c89-904b-721d513a8ac8
		summarizeBy: none
		sourceColumn: CaseID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column FromDate
		dataType: dateTime
		formatString: Short Date
		lineageTag: 2800adcc-d8db-4489-94f6-ead4b05e4498
		summarizeBy: none
		sourceColumn: FromDate

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column ThruDate
		dataType: dateTime
		formatString: Short Date
		lineageTag: 01548ff2-4d98-4c39-9031-ef0d45aed16b
		summarizeBy: none
		sourceColumn: ThruDate

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column PayorType
		dataType: string
		lineageTag: 2ac41e77-e097-4c80-a9ca-dfa36f1ea656
		summarizeBy: none
		sourceColumn: PayorType

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Payer_ID
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: efe31194-3641-4df2-ba06-70f5bd9e353f
		summarizeBy: none
		sourceColumn: Payer_ID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Payer Group' =
			
			// SWITCH(
			//     RELATED(Payers[Name]),
			//     "Medicare Part A","(1) Medicare A",
			//     "Medicare Part B","(3) Medicare B",
			//     SWITCH(
			//         vw_PatientPayers[PayorType],
			//         "Medicare Part A","(2) Managed A",
			//         "Managed Care Part A","(2) Managed A",
			//         "Medicare Part B",IF(vw_PatientPayers[Payer_ID] IN {550, 1389},"(5) ISNP B","(4) Managed B"),
			//         "Managed Care Part B",IF(vw_PatientPayers[Payer_ID] IN {550, 1389},"(5) ISNP B","(4) Managed B"),
			//         // "Managed Care Part B","(4) Managed B",
			//         "Medicaid","(6) Medicaid",
			//         "(7) Other"
			//     )
			// )
			
			SWITCH(
			    vw_PatientPayers[PayorType],
			    "Medicare Part A","(1) Medicare A",
			    "Managed Care Part A","(2) Managed A",
			    "Medicare Part B",IF(vw_PatientPayers[Payer_ID] IN {550, 1389},"(5) ISNP B","(3) Medicare B"),
			    "Managed Care Part B",IF(vw_PatientPayers[Payer_ID] IN {550, 1389},"(5) ISNP B","(4) Managed B"),
			    "Medicaid","(6) Medicaid",
			    "(7) Other"
			)
		lineageTag: 8cfcb6a0-0030-42c2-9440-13a4d560b0b6
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column Days =
			
			DATEDIFF(
			    vw_PatientPayers[FromDate]-1,
			    vw_PatientPayers[ThruDate],
			    DAY
			)
		formatString: #,0
		lineageTag: d31df6f6-224c-4f5f-bb68-1a0397f2e286
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	partition vw_PatientPayers = m
		mode: import
		queryGroup: Payer
		source =
				let
				    Source = Value.NativeQuery(_NetHealthBronze, "SELECT cps.PatientCase_ID AS CaseID, cps.FromDate, cps.ThruDate, pt.Descrip AS PayorType, ppt.Payer_ID FROM dbo.CasePayerSet cps INNER JOIN dbo.ResidentPayerSequence seq ON seq.ResidentPayerSet_ID = cps.ResidentPayerSet_ID AND seq.Sequence = 1 INNER JOIN dbo.ResidentPayer rp ON rp.ResidentPayer_ID = seq.ResidentPayer_ID INNER JOIN dbo.PayerPayerType ppt ON ppt.PayerPayerType_ID = rp.PayerPayerType_ID INNER JOIN dbo.PayerType pt ON pt.PayerType_ID = ppt.PayerType_ID WHERE cps.PatientCase_ID IN " & _QualifyingCaseIdsSql),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"FromDate", type date}, {"ThruDate", type date}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

